# -*- coding: utf-8 -*- 
#based on http://docs.equest.com/eQuestCountryAndStateCodes.xls
_dic = {u"AF-BDS": u"Badakhshān",
u"AF-BDG": u"Bādghīs",
u"AF-BGL": u"Baghlān",
u"AF-BAL": u"Balkh",
u"AF-BAM": u"Bāmīān",
u"AF-FRA": u"Farāh",
u"AF-FYB": u"Fāryāb",
u"AF-GHA": u"Ghaznī",
u"AF-GHO": u"Ghowr",
u"AF-HEL": u"Helmand",
u"AF-HER": u"Herāt",
u"AF-JOW": u"Jowzjān",
u"AF-KAB": u"Kabul (Kābol)",
u"AF-KAN": u"Kandahār",
u"AF-KAP": u"Kāpīsā",
u"AF-KNR": u"Konar (Kunar)",
u"AF-KDZ": u"Kondoz (Kunduz)",
u"AF-LAG": u"Laghmān",
u"AF-LOW": u"Lowgar",
u"AF-NAN": u"Nangrahār (Nangarhār)",
u"AF-NIM": u"Nīmrūz",
u"AF-ORU": u"Orūzgān (Urūzgā",
u"AF-PIA": u"Paktīā",
u"AF-PKA": u"Paktīkā",
u"AF-PAR": u"Parwān",
u"AF-SAM": u"Samangān",
u"AF-SAR": u"Sar-e Pol",
u"AF-TAK": u"Takhār",
u"AF-WAR": u"Wardak (Wardag)",
u"AF-ZAB": u"Zābol (Zābul)",
u"AL-BR": u"Berat",
u"AL-BU": u"Bulqizë",
u"AL-DL": u"Delvinë",
u"AL-DV": u"Devoll",
u"AL-DI": u"Dibër",
u"AL-DR": u"Durrës",
u"AL-EL": u"Elbasan",
u"AL-FR": u"Fier",
u"AL-GR": u"Gramsh",
u"AL-GJ": u"Gjirokastër",
u"AL-HA": u"Has",
u"AL-KA": u"Kavajë",
u"AL-ER": u"Kolonjë",
u"AL-KO": u"Korcë",
u"AL-KR": u"Krujë",
u"AL-KC": u"Kucovë",
u"AL-KU": u"Kukës",
u"AL-LA": u"Laç",
u"AL-LE": u"Lezhë",
u"AL-LB": u"Librazhd",
u"AL-LU": u"Lushnjë",
u"AL-MM": u"Malësia e Madhe",
u"AL-MK": u"Mallakastër",
u"AL-MT": u"Mat",
u"AL-MR": u"Mirditë",
u"AL-PQ": u"Peqin",
u"AL-PR": u"Përmet",
u"AL-PG": u"Pogradec",
u"AL-PU": u"Pukë",
u"AL-SR": u"Sarandë",
u"AL-SK": u"Skrapar",
u"AL-SH": u"Shkodër",
u"AL-TE": u"Tepelenë",
u"AL-TR": u"Tiranë",
u"AL-TP": u"Tropojë",
u"AL-VL": u"Vlorë",
u"DZ-01": u"Adrar",
u"DZ-44": u"Aïn Defla",
u"DZ-46": u"Aïn Témouchent",
u"DZ-16": u"Alger",
u"DZ-05": u"Batna",
u"DZ-08": u"Béchar",
u"DZ-06": u"Béjaïa",
u"DZ-07": u"Biskra",
u"DZ-09": u"Blida",
u"DZ-34": u"Bordj Bou Arréridj",
u"DZ-10": u"Bouira",
u"DZ-35": u"Boumerdès",
u"DZ-02": u"Chlef",
u"DZ-25": u"Constantine",
u"DZ-17": u"Djelfa",
u"DZ-32": u"El Bayadh",
u"DZ-39": u"El Oued",
u"DZ-36": u"El Tarf",
u"DZ-47": u"Ghardaïa",
u"DZ-24": u"Guelma",
u"DZ-33": u"Illizi",
u"DZ-18": u"Jijel",
u"DZ-40": u"Khenchela",
u"DZ-03": u"Laghouat",
u"DZ-29": u"Mascara",
u"DZ-26": u"Médéa",
u"DZ-43": u"Mila",
u"DZ-27": u"Mostaganem",
u"DZ-28": u"Msila",
u"DZ-45": u"Naama",
u"DZ-31": u"Oran",
u"DZ-30": u"Ouargla",
u"DZ-04": u"Oum el Bouaghi",
u"DZ-48": u"Relizane",
u"DZ-20": u"Saïda",
u"DZ-19": u"Sétif",
u"DZ-22": u"Sidi Bel Abbès",
u"DZ-21": u"Skikda",
u"DZ-41": u"Souk Ahras",
u"DZ-11": u"Tamanghasset",
u"DZ-12": u"Tébessa",
u"DZ-14": u"Tiaret",
u"DZ-37": u"Tindouf",
u"DZ-42": u"Tipaza",
u"DZ-38": u"Tissemsilt",
u"DZ-15": u"Tizi Ouzou",
u"DZ-13": u"Tlemcen",
u"AS-AS": u"American Samoa",
u"AD-AD": u"Andorra",
u"AO-BGO": u"Bengo",
u"AO-BGU": u"Benguela",
u"AO-BIE": u"Bié",
u"AO-CAB": u"Cabinda",
u"AO-CCU": u"Cuando-Cubango",
u"AO-CNO": u"Cuanza Norte",
u"AO-CUS": u"Cuanza Sul",
u"AO-CNN": u"Cunene",
u"AO-HUA": u"Huambo",
u"AO-HUI": u"Huíla",
u"AO-LUA": u"Luanda",
u"AO-LNO": u"Lunda Norte",
u"AO-LSU": u"Lunda Sul",
u"AO-MAL": u"Malange",
u"AO-MOX": u"Moxico",
u"AO-NAM": u"Namibe",
u"AO-UIG": u"Uíge",
u"AO-ZAI": u"Zaïre",
u"AI-AI": u"Anguilla",
u"AQ-AQ": u"Antarctica",
u"AG-AG": u"Antigua & Barbuda",
u"AR-C": u"Capital federal",
u"AR-B": u"Buenos Aires",
u"AR-K": u"Catamarca",
u"AR-X": u"Córdoba",
u"AR-W": u"Corrientes",
u"AR-H": u"Chaco",
u"AR-U": u"Chubut",
u"AR-E": u"Entre Ríos",
u"AR-P": u"Formosa",
u"AR-Y": u"Jujuy",
u"AR-L": u"La Pampa",
u"AR-F": u"La Rioja",
u"AR-M": u"Mendoza",
u"AR-N": u"Misiones",
u"AR-Q": u"Neuquén",
u"AR-R": u"Río Negro",
u"AR-A": u"Salta",
u"AR-J": u"San Juan",
u"AR-D": u"San Luis",
u"AR-Z": u"Santa Cruz",
u"AR-S": u"Santa Fe",
u"AR-G": u"Santiago del Estero",
u"AR-V": u"Tierra del Fuego",
u"AR-T": u"Tucumán",
u"AM-ER": u"Erevan",
u"AM-AG": u"Aragacotn",
u"AM-AR": u"Ararat",
u"AM-AV": u"Armavir",
u"AM-GR": u"Geģark'unik'",
u"AM-KT": u"Kotayk'",
u"AM-LO": u"Loŕy",
u"AM-SH": u"Širak",
u"AM-SU": u"Syunik'",
u"AM-TV": u"Tavuš",
u"AM-VD": u"Vayoc Jor",
u"AW-AW": u"Aruba",
u"AU-NSW": u"New South Wales",
u"AU-QLD": u"Queensland",
u"AU-SA": u"South Australia",
u"AU-TAS": u"Tasmania",
u"AU-VIC": u"Victoria",
u"AU-WA": u"Western Australia",
u"AU-ACT": u"Australian Capital Territory",
u"AU-NT": u"Northern Territory",
u"AT-1": u"Burgenland",
u"AT-2": u"Kärnten",
u"AT-3": u"Niederösterreich",
u"AT-4": u"Oberösterreich",
u"AT-5": u"Salzburg",
u"AT-6": u"Steiermark",
u"AT-7": u"Tirol",
u"AT-8": u"Vorarlberg",
u"AT-9": u"Wien",
u"AZ-MM": u"Naxçivan",
u"AZ-AB": u"Äli Bayramli",
u"AZ-BA": u"Baki",
u"AZ-GA": u"Gäncä",
u"AZ-LA": u"Länkäran",
u"AZ-MI": u"Mingäçevir",
u"AZ-NA": u"Naftalan",
u"AZ-SA": u"Şäki",
u"AZ-SM": u"Sumqayit",
u"AZ-SS": u"Şuşa",
u"AZ-XA": u"Xankändi",
u"AZ-YE": u"Yevlax",
u"AZ-ABS": u"Abşeron",
u"AZ-AGC": u"Ağcabädi",
u"AZ-AGM": u"Ağdam",
u"AZ-AGS": u"Ağdas",
u"AZ-AGA": u"Ağstafa",
u"AZ-AGU": u"Ağsu",
u"AZ-AST": u"Astara",
u"AZ-BAB": u"Babäk",
u"AZ-BAL": u"Balakän",
u"AZ-BAR": u"Bärdä",
u"AZ-BEY": u"Beyläqan",
u"AZ-BIL": u"Biläsuvar",
u"AZ-CAB": u"Cäbrayil",
u"AZ-CAL": u"Cälilabad",
u"AZ-CUL": u"Culfa",
u"AZ-DAS": u"Daşkäsän",
u"AZ-DAV": u"Däväçi",
u"AZ-FUZ": u"Füzuli",
u"AZ-GAD": u"Gädäbäy",
u"AZ-GOR": u"Goranboy",
u"AZ-GOY": u"Göyçay",
u"AZ-HAC": u"Haciqabul",
u"AZ-IMI": u"Imişli",
u"AZ-ISM": u"Ismayilli",
u"AZ-KAL": u"Kälbäcär",
u"AZ-KUR": u"Kürdämir",
u"AZ-LAC": u"Laçin",
u"AZ-LAN": u"Länkäran",
u"AZ-LER": u"Lerik",
u"AZ-MAS": u"Masalli",
u"AZ-NEF": u"Neftçala",
u"AZ-OGU": u"Oğuz",
u"AZ-ORD": u"Ordubad",
u"AZ-QAB": u"Qäbälä",
u"AZ-QAX": u"Qax",
u"AZ-QAZ": u"Qazax",
u"AZ-QOB": u"Qobustan",
u"AZ-QBA": u"Quba",
u"AZ-QBI": u"Qubadlı",
u"AZ-QUS": u"Qusar",
u"AZ-SAT": u"Saatli",
u"AZ-SAB": u"Sabirabad",
u"AZ-SAD": u"Sädäräk",
u"AZ-SAH": u"Şahbuz",
u"AZ-SAK": u"Şäki",
u"AZ-SAL": u"Salyan",
u"AZ-SMI": u"Şamaxı",
u"AZ-SKR": u"Şämkir",
u"AZ-SMX": u"Samux",
u"AZ-SAR": u"Şärur",
u"AZ-SIY": u"Siyäzän",
u"AZ-SUS": u"Şuşa",
u"AZ-TAR": u"Tärtär",
u"AZ-TOV": u"Tovuz",
u"AZ-UCA": u"Ucar",
u"AZ-XAC": u"Xaçmaz",
u"AZ-XAN": u"Xanlar",
u"AZ-XIZ": u"Xizi",
u"AZ-XCI": u"Xocalı",
u"AZ-XVD": u"Xocavänd",
u"AZ-YAR": u"Yardimli",
u"AZ-YEV": u"Yevlax",
u"AZ-ZAN": u"Zängılan",
u"AZ-ZAQ": u"Zaqatala",
u"AZ-ZAR": u"Zärdab",
u"BS-AC": u"Acklins and Crooked Islands",
u"BS-BI": u"Bimini",
u"BS-CI": u"Cat Island",
u"BS-EX": u"Exuma",
u"BS-FP": u"Freeport",
u"BS-FC": u"Fresh Creek",
u"BS-GH": u"Governor's Harbour",
u"BS-GT": u"Green Turtle Cay",
u"BS-HI": u"Harbour Island",
u"BS-HR": u"High Rock",
u"BS-IN": u"Inagua",
u"BS-KB": u"Kemps Bay",
u"BS-LI": u"Long Island",
u"BS-MH": u"Marsh Harbour",
u"BS-MG": u"Mayaguana",
u"BS-NP": u"New Providence",
u"BS-NB": u"Nicholls Town and Berry Islands",
u"BS-RI": u"Ragged Island",
u"BS-RS": u"Rock Sound",
u"BS-SP": u"Sandy Point",
u"BS-SR": u"San Salvador and Rum Cay",
u"BH-01": u"Al Ḩadd",
u"BH-03": u"Al Manāmah",
u"BH-10": u"Al Minţaqah al Gharbīyah",
u"BH-07": u"Al Minţaqah al Wusţa",
u"BH-05": u"Al Minţaqah ash Shamālīyah",
u"BH-02": u"Al Muḩarraq",
u"BH-09": u"Ar Rifā‘",
u"BH-04": u"Jidd Ḩafş",
u"BH-12": u"Madīnat Ḩamad",
u"BH-08": u"Madīnat ‘Īsá",
u"BH-11": u"Minţaqat Juzur Ḩawār",
u"BH-06": u"Sitrah",
u"BD-1": u"Barisal bibhag",
u"BD-1B": u"Barisal anchal",
u"BD-1Q": u"Patuakhali anchal",
u"BD-2": u"Chittagong bibhag",
u"BD-2A": u"Bandarban anchal",
u"BD-2D": u"Chittagong anchal",
u"BD-2E": u"Chittagong Hill Tracts",
u"BD-2F": u"Comilla anchal",
u"BD-2O": u"Noakhali anchal",
u"BD-2T": u"Sylhet anchal",
u"BD-3": u"Dhaka bibhag",
u"BD-3G": u"Dhaka anchal",
u"BD-3I": u"Faridpur anchal",
u"BD-3J": u"Jamalpur anchal",
u"BD-3N": u"Mymensingh anchal",
u"BD-3U": u"Tangail anchal",
u"BD-4": u"Khulna bibhag",
u"BD-4K": u"Jessore anchal",
u"BD-4L": u"Khulna anchal",
u"BD-4M": u"Khustia anchal",
u"BD-5": u"Rajshahi bibhag",
u"BD-5C": u"Bogra anchal",
u"BD-5H": u"Dinajpur anchal",
u"BD-5P": u"Pabna anchal",
u"BD-5R": u"Rajshahi anchal",
u"BD-5S": u"Rangpur anchal",
u"BB-BB": u"Barbados",
u"BY-BR": u"Brestskaya voblasts'",
u"BY-HO": u"Homyel'skaya voblasts’",
u"BY-HR": u"Hrodnenskaya voblasts'",
u"BY-MA": u"Mahilyowskaya voblasts'",
u"BY-MI": u"Minskaya voblasts'",
u"BY-VI": u"Vitsyebskaya voblasts'",
u"BE-BRU": u"Bruxelles-Capitale, Region de (fr), Brussels Hoofdstedelijk Gewest (nl)",
u"BE-VLG": u"Vlaamse Gewest (nl)",
u"BE-VAN": u"Antwerpen (nl)",
u"BE-VLI": u"Limburg (nl)",
u"BE-VOV": u"Oost-Vlaanderen (nl)",
u"BE-VBR": u"Vlaams Brabant (nl)",
u"BE-VWV": u"West-Vlaanderen (nl)",
u"BE-WAL": u"Wallonne, Region (fr)",
u"BE-WBR": u"Brabant Wallon (fr)",
u"BE-WHT": u"Hainaut (fr)",
u"BE-WLG": u"Liège (fr)",
u"BE-WLX": u"Luxembourg (fr)",
u"BE-WNA": u"Namur (fr)",
u"BZ-BZ": u"Belize",
u"BZ-CY": u"Cayo",
u"BZ-CZL": u"Corozal",
u"BZ-OW": u"Orange Walk",
u"BZ-SC": u"Stann Creek",
u"BZ-TOL": u"Toledo",
u"BJ-AK": u"Atakora",
u"BJ-AQ": u"Atlantique",
u"BJ-BO": u"Borgou",
u"BJ-MO": u"Mono",
u"BJ-OU": u"Ouémé",
u"BJ-ZO": u"Zou",
u"BM-BM": u"Bermuda",
u"BT-33": u"Bumthang",
u"BT-12": u"Chhukha",
u"BT-22": u"Dagana",
u"BT-GA": u"Gasa",
u"BT-13": u"Ha",
u"BT-44": u"Lhuentse",
u"BT-42": u"Monggar",
u"BT-11": u"Paro",
u"BT-43": u"Pemagatshel",
u"BT-23": u"Punakha",
u"BT-45": u"Samdrup Jongkha",
u"BT-14": u"Samtse",
u"BT-31": u"Sarpang",
u"BT-15": u"Thimphu",
u"BT-41": u"Trashigang",
u"BT-TY": u"Trashi Yangtse",
u"BT-32": u"Trongsa",
u"BT-21": u"Tsirang",
u"BT-24": u"Wangdue Phodrang",
u"BT-34": u"Zhemgang",
u"BO-C": u"Cochabamba",
u"BO-H": u"Chuquisaca",
u"BO-B": u"El Beni",
u"BO-L": u"La Paz",
u"BO-O": u"Oruro",
u"BO-N": u"Pando",
u"BO-P": u"Potosi",
u"BO-S": u"Santa Cruz",
u"BO-T": u"Tarija",
u"BA-BIH": u"Federacija Bosna i Hercegovina",
u"BA-SRP": u"Republika Srpska",
u"BW-CE": u"Central [Serowe-Palapye]",
u"BW-CH": u"Chobe",
u"BW-GH": u"Ghanzi",
u"BW-KG": u"Kgalagadi",
u"BW-KL": u"Kgatleng",
u"BW-KW": u"Kweneng",
u"BW-NG": u"Ngamiland [North-West]",
u"BW-NE": u"North-East",
u"BW-SE": u"South-East",
u"BW-SO": u"Southern [Ngwaketse]",
u"BV-BV": u"Bouvet Island",
u"BR-DF": u"Distrito Federal",
u"BR-AC": u"Acre",
u"BR-AL": u"Alagoas",
u"BR-AP": u"Amapá",
u"BR-AM": u"Amazonas",
u"BR-BA": u"Bahia",
u"BR-CE": u"Ceará",
u"BR-ES": u"Espírito Santo",
u"BR-GO": u"Goiás",
u"BR-MA": u"Maranhāo",
u"BR-MT": u"Mato Grosso",
u"BR-MS": u"Mato Grosso do Sul",
u"BR-MG": u"Minas Gerais",
u"BR-PA": u"Pará",
u"BR-PB": u"Paraíba",
u"BR-PR": u"Paraná",
u"BR-PE": u"Pernambuco",
u"BR-PI": u"Piauí",
u"BR-RJ": u"Rio de Janeiro",
u"BR-RN": u"Rio Grande do Norte",
u"BR-RS": u"Rio Grande do Sul",
u"BR-R0": u"Rondônia",
u"BR-RR": u"Roraima",
u"BR-SC": u"Santa Catarina",
u"BR-SP": u"São Paulo",
u"BR-SE": u"Sergipe",
u"BR-TO": u"Tocantins",
u"IO-IO": u"British Indian Ocean Territory",
u"BN-BE": u"Belait",
u"BN-BM": u"Brunei-Muara",
u"BN-TE": u"Temburong",
u"BN-TU": u"Tutong",
u"BG-02": u"Burgas",
u"BG-09": u"Haskovo",
u"BG-04": u"Loveč",
u"BG-05": u"Montana",
u"BG-06": u"Plovdiv",
u"BG-07": u"Ruse",
u"BG-08": u"Sofija",
u"BG-01": u"Sofija-Grad",
u"BG-03": u"Varna",
u"BF-BAL": u"Balé",
u"BF-BAM": u"Bam",
u"BF-BAN": u"Banwa",
u"BF-BAZ": u"Bazèga",
u"BF-BGR": u"Bougouriba",
u"BF-BLG": u"Boulgou",
u"BF-BLK": u"Boulkiemdé",
u"BF-COM": u"Comoé",
u"BF-GAN": u"Ganzourgou",
u"BF-GNA": u"Gnagna",
u"BF-GOU": u"Gourma",
u"BF-HOU": u"Houet",
u"BF-IOB": u"Ioba",
u"BF-KAD": u"Kadiogo",
u"BF-KEN": u"Kénédougou",
u"BF-KMD": u"Komondjari",
u"BF-KMP": u"Kompienga",
u"BF-KOS": u"Kossi",
u"BF-KOP": u"Koulpélogo",
u"BF-KOT": u"Kouritenga",
u"BF-KOW": u"Kourwéogo",
u"BF-LER": u"Léraba",
u"BF-LOR": u"Loroum",
u"BF-MOU": u"Mouhoun",
u"BF-NAO": u"Nahouri",
u"BF-NAM": u"Namentenga",
u"BF-NAY": u"Nayala",
u"BF-NOU": u"Noumbiel",
u"BF-OUB": u"Oubritenga",
u"BF-OUD": u"Oudalan",
u"BF-PAS": u"Passoré",
u"BF-PON": u"Poni",
u"BF-SNG": u"Sanguié",
u"BF-SMT": u"Sanmatenga",
u"BF-SEN": u"Séno",
u"BF-SIS": u"Sissili",
u"BF-SOM": u"Soum",
u"BF-SOR": u"Sourou",
u"BF-TAP": u"Tapoa",
u"BF-TUI": u"Tui",
u"BF-YAG": u"Yagha",
u"BF-YAT": u"Yatenga",
u"BF-ZIR": u"Ziro",
u"BF-ZON": u"Zondoma",
u"BF-ZOU": u"Zoundwéogo",
u"BI-BB": u"Bubanza",
u"BI-BJ": u"Bujumbura",
u"BI-BR": u"Bururi",
u"BI-CA": u"Cankuzo",
u"BI-CI": u"Cibitoke",
u"BI-GI": u"Gitega",
u"BI-KR": u"Karuzi",
u"BI-KY": u"Kayanza",
u"BI-KI": u"Kirundo",
u"BI-MA": u"Makamba",
u"BI-MU": u"Muramvya",
u"BI-MY": u"Muyinga",
u"BI-NG": u"Ngozi",
u"BI-RT": u"Rutana",
u"BI-RY": u"Ruyigi",
u"KH-23": u"Krong Kaeb [Krŏng Kêb]",
u"KH-18": u"Krong Preah Sihanouk [Krŏng Preăh Sihanouk]",
u"KH-12": u"Phnom Penh [Phnum Pénh]",
u"KH-2": u"Baat Dambang [Bătdâmbâng]",
u"KH-1": u"Banteay Mean Chey [Bântéay Méanchey]",
u"KH-3": u"Kampong Chaam [Kâmpóng Cham]",
u"KH-4": u"Kampong Chhnang [Kâmpóng Chhnăng]",
u"KH-5": u"Kampong Spueu [Kâmpóng Spœ]",
u"KH-6": u"Kampong Thum [Kâmpóng Thum]",
u"KH-7": u"Kampot [Kâmpôt]",
u"KH-8": u"Kandaal [Kândal]",
u"KH-10": u"Kracheh [Krâchéh]",
u"KH-11": u"Mond01 Kiri [Môndól Kiri]",
u"KH-22": u"Otdar Mean Chey [Ŏtdâr Méanchey]",
u"KH-15": u"Pousaat [Poŭthĭsăt]",
u"KH-13": u"Preah Vihear [Preăh Vihéar]",
u"KH-14": u"Prey Veaeng [Prey Vêng]",
u"KH-16": u"Rotanak Kiri [Rôtânôkiri]",
u"KH-17": u"Siem Reab [Siĕmréab]",
u"KH-19": u"Stueng Traeng [Stœng Trêng]",
u"KH-20": u"Svaay Rieng [Svay Riĕng]",
u"KH-21": u"Taakaev [Takêv]",
u"CM-AD": u"Adamaoua",
u"CM-CE": u"Centre",
u"CM-ES": u"Est",
u"CM-EN": u"Far North",
u"CM-LT": u"Littoral",
u"CM-NO": u"North",
u"CM-NW": u"North-West",
u"CM-SU": u"South",
u"CM-SW": u"South-West",
u"CM-OU": u"West",
u"CA-AB": u"Alberta",
u"CA-BC": u"British Columbia (Colombie-Britannique)",
u"CA-MB": u"Manitoba",
u"CA-NB": u"New Brunswick (Nouveau-Brunswick)",
u"CA-NF": u"Newfoundland (Terre-Neuve)",
u"CA-NS": u"Nova Scotia (Nouvelle-Écosse)",
u"CA-ON": u"Ontario",
u"CA-PE": u"Printe Edward Island (Île-du-Prince-Édouard)",
u"CA-QC": u"Quebec (Québec)",
u"CA-SK": u"Saskatchewan",
u"CA-NT": u"Northwest Territories (Territoires du Nord-Ouest)",
u"CA-YT": u"Yukon Territory (Teritoire du Yukon)",
u"CV-B": u"Ilhas de Barlavento",
u"CV-BV": u"Boa Vista",
u"CV-PA": u"Paul",
u"CV-PN": u"Porto Novo",
u"CV-RG": u"Ribeira Grande",
u"CV-SL": u"Sal",
u"CV-SN": u"Sāo Nicolau",
u"CV-SV": u"Sāo Vicente",
u"CV-S": u"Ilhas de Sotavento",
u"CV-BR": u"Brava",
u"CV-FO": u"Fogo",
u"CV-MA": u"Maio",
u"CV-PR": u"Praia",
u"CV-CA": u"Santa Catarina",
u"CV-CR": u"Santa Cruz",
u"CV-TA": u"Tarrafal",
u"KY-KY": u"Cayman Islands",
u"CF-BGF": u"Bangui",
u"CF-BB": u"Bamingui-Bangoran",
u"CF-BK": u"Basse-Kotto",
u"CF-HK": u"Haute-Kotto",
u"CF-HM": u"Haut-Mbomou",
u"CF-KG": u"Kémo",
u"CF-LB": u"Lobaye",
u"CF-HS": u"Mambéré-Kadéï",
u"CF-MB": u"Mbomou",
u"CF-KB": u"Nana-Grébizi",
u"CF-NM": u"Nana-Mambéré",
u"CF-MP": u"Ombella-Mpoko",
u"CF-UK": u"Ouaka",
u"CF-AC": u"Ouham",
u"CF-OP": u"Ouham-Pendé",
u"CF-SE": u"Sangha-Mbaéré",
u"CF-VK": u"Vakaga",
u"TD-BA": u"Batha",
u"TD-BI": u"Biltine",
u"TD-BET": u"Borkou-Ennedi-Tibesti",
u"TD-CB": u"Chari-Baguirmi",
u"TD-GR": u"Guéra",
u"TD-KA": u"Kanem",
u"TD-LC": u"Lac",
u"TD-LO": u"Logone-Occidental",
u"TD-LR": u"Logone-Oriental",
u"TD-MK": u"Mayo-Kébbi",
u"TD-MC": u"Moyen-Chari",
u"TD-OD": u"Ouaddaï",
u"TD-SA": u"Salamat",
u"TD-TA": u"Tandjilé",
u"CL-AI": u"Aisén del General Carlos Ibáñiez del Campo",
u"CL-AN": u"Antofagasta",
u"CL-AR": u"Araucanía",
u"CL-AT": u"Atacama",
u"CL-BI": u"Bío-Bío",
u"CL-CO": u"Coquimbo",
u"CL-LI": u"Libertador General Bernardo O'Higgins",
u"CL-LL": u"Los Lagos",
u"CL-MA": u"Magallanes",
u"CL-ML": u"Maule",
u"CL-RM": u"Regíon Metropolitana de Santiago",
u"CL-TA": u"Tarapacá",
u"CL-VS": u"Valparaiso",
u"CN-11": u"Beijing",
u"CN-50": u"Chongqing",
u"CN-31": u"Shanghai",
u"CN-12": u"Tianjin",
u"CN-34": u"Anhui",
u"CN-35": u"Fujian",
u"CN-62": u"Gansu",
u"CN-44": u"Guangdong",
u"CN-52": u"Guizhou",
u"CN-46": u"Hainan",
u"CN-13": u"Hebei",
u"CN-23": u"Heilongjiang",
u"CN-41": u"Henan",
u"CN-42": u"Hubei",
u"CN-43": u"Hunan",
u"CN-32": u"Jiangsu",
u"CN-36": u"Jiangxi",
u"CN-22": u"Jilin",
u"CN-21": u"Liaoning",
u"CN-63": u"Qinghai",
u"CN-61": u"Shaanxi",
u"CN-37": u"Shandong",
u"CN-14": u"Shanxi",
u"CN-51": u"Sichuan",
u"CN-71": u"Taiwan",
u"CN-53": u"Yunnan",
u"CN-33": u"Zhejiang",
u"CN-45": u"Guangxi",
u"CN-15": u"Nei Monggol",
u"CN-64": u"Ningxia",
u"CN-65": u"Xinjiang",
u"CN-54": u"Xizang",
u"CN-91": u"Hong Kong",
u"CX-CX": u"Christmas Island",
u"CC-CC": u"Cocos (Keeling) Islands",
u"CO-DC": u"Distrito Capital de Santa Fe de Bogota",
u"CO-AMA": u"Amazonas",
u"CO-ANT": u"Antioguia",
u"CO-ARA": u"Arauca",
u"CO-ATL": u"Atlántico",
u"CO-BOL": u"Bolívar",
u"CO-BOY": u"Boyacá",
u"CO-CAL": u"Caldas",
u"CO-CAQ": u"Caquetá",
u"CO-CAS": u"Casanare",
u"CO-CAU": u"Cauca",
u"CO-CES": u"Cesar",
u"CO-COR": u"Córdoba",
u"CO-CUN": u"Cundinamarca",
u"CO-CHO": u"Chocó",
u"CO-GUA": u"Guainía",
u"CO-GUV": u"Guaviare",
u"CO-HUI": u"Huila",
u"CO-LAG": u"La Guajira",
u"CO-MAG": u"Magdalena",
u"CO-MET": u"Meta",
u"CO-NAR": u"Nariño",
u"CO-NSA": u"Norte de Santander",
u"CO-PUT": u"Putumayo",
u"CO-QUI": u"Quindío",
u"CO-RIS": u"Risaralda",
u"CO-SAP": u"San Andrés, Providencia y Santa Catalina",
u"CO-SAN": u"Santander",
u"CO-SUC": u"Sucre",
u"CO-TOL": u"Tolima",
u"CO-VAC": u"Valle del Cauca",
u"CO-VAU": u"Vaupés",
u"CO-VID": u"Vichada",
u"KM-A": u"Anjouan (Ndzouani)",
u"KM-G": u"Grande Comore (Ngazidja)",
u"KM-M": u"Mohéli (Moili)",
u"CG-BZV": u"Brazzaville",
u"CG-11": u"Bouenza",
u"CG-8": u"Cuvette",
u"CG-15": u"Cuvette-Ouest",
u"CG-5": u"Kouilou",
u"CG-2": u"Lékoumou",
u"CG-7": u"Likouala",
u"CG-9": u"Niari",
u"CG-14": u"Plateaux",
u"CG-12": u"Pool",
u"CG-13": u"Sangha",
u"CD-KN": u"Kinshasa",
u"CD-BN": u"Bandundu",
u"CD-BC": u"Bas-Congo",
u"CD-EQ": u"Équateur",
u"CD-HC": u"Haut-Congo",
u"CD-KW": u"Kasai-Occidental",
u"CD-KE": u"Kasai-Oriental",
u"CD-KA": u"Katanga",
u"CD-MA": u"Maniema",
u"CD-NK": u"Nord-Kivu",
u"CD-SK": u"Sud-Kivu",
u"CK-CK": u"Cook Islands",
u"CR-A": u"Alajuela",
u"CR-C": u"Cartago",
u"CR-G": u"Guanacaste",
u"CR-H": u"Heredia",
u"CR-L": u"Limón",
u"CR-P": u"Puntarenas",
u"CR-SJ": u"San José",
u"CI-06": u"18 Montagnes (Région des)",
u"CI-16": u"Agnébi (Région de l')",
u"CI-09": u"Bas-Sassandra (Région du)",
u"CI-10": u"Denguélé (Région du)",
u"CI-02": u"Haut-Sassandra (Région du)",
u"CI-07": u"Lacs (Région des)",
u"CI-01": u"Lagunes (Région des)",
u"CI-12": u"Marahoué (Région de la)",
u"CI-05": u"Moyen-Comoé (Région du)",
u"CI-11": u"Nzi-Comoé (Région)",
u"CI-03": u"Savanes (Région des)",
u"CI-15": u"Sud-Bandama (Région du)",
u"CI-13": u"Sud-Comoé (Région du)",
u"CI-04": u"Vallée du Bandama (Région de la)",
u"CI-14": u"Worodougou (Région du)",
u"CI-08": u"Zanzan (Région du)",
u"HR-07": u"Bjelovarsko-bilogorska županija",
u"HR-12": u"Brodsko-posavska županija",
u"HR-19": u"Dubrovačko-neretvanska županija",
u"HR-18": u"Istarska županija",
u"HR-04": u"Karlovačka županija",
u"HR-06": u"Koprivničkco-križevačka županija",
u"HR-02": u"Krapinsko-zagorska županija",
u"HR-09": u"Ličko-senjska županija",
u"HR-20": u"Medjimurska županija",
u"HR-14": u"Osječko-baranjska županija",
u"HR-11": u"Požeško-slavonska županija",
u"HR-08": u"Primorsko-goranska županija",
u"HR-03": u"Sisaško-moslavačka županija",
u"HR-17": u"Splitsko-dalmatinska županija",
u"HR-15": u"Šibensko-kninska županija",
u"HR-05": u"Varaždinska županija",
u"HR-10": u"Virovitičko-podravska županija",
u"HR-16": u"Vukovarsko-srijemska županija",
u"HR-13": u"Zadarska županija",
u"HR-01": u"Zagrebačka županija",
u"CU-09": u"Camagüey",
u"CU-03": u"Ciudad de La Habana",
u"CU-12": u"Granma",
u"CU-14": u"Guantánamo",
u"CU-11": u"Holguín",
u"CU-02": u"La Habana",
u"CU-10": u"Las Tunas",
u"CU-04": u"Matanzas",
u"CU-01": u"Pinar del Río",
u"CU-07": u"Sancti Spíritus",
u"CU-13": u"Santiago de Cuba",
u"CU-05": u"Villa Clara",
u"CU-99": u"Isla de la Juventud",
u"CY-04": u"Ammochostos (Mağusa)",
u"CY-06": u"Keryneia (Girne)",
u"CY-03": u"Larnaka",
u"CY-01": u"Lefkosia (Lefkoşa)",
u"CY-02": u"Lemesos (Leymosun)",
u"CY-05": u"Pafos (Baf)",
u"CZ-PRG": u"Praha",
u"CZ-CJC": u"Jihočeský kraj",
u"CZ-CJM": u"Jihomoravský kraj",
u"CZ-CSC": u"Severočeský kraj",
u"CZ-CSM": u"Severomoravský kraj",
u"CZ-CST": u"Středočeský kraj",
u"CZ-CVC": u"Východočeský kraj",
u"CZ-CZC": u"Západočeský kraj",
u"DK-147": u"Frederiksberg",
u"DK-101": u"Kǿbenhavn",
u"DK-040": u"Bornholm",
u"DK-020": u"Frederiksborg",
u"DK-042": u"Fyn",
u"DK-015": u"Kǿbenhavn",
u"DK-080": u"Nordjylland",
u"DK-055": u"Ribe",
u"DK-065": u"Ringkǿbing",
u"DK-025": u"Roskilde",
u"DK-035": u"Storstrǿm",
u"DK-050": u"Sǿnderjylland",
u"DK-060": u"Vejle",
u"DK-030": u"Vestsjælland",
u"DK-076": u"Viborg",
u"DK-070": u"Århus",
u"DJ-AS": u"Ali Sabieh",
u"DJ-DI": u"Dikhil",
u"DJ-DJ": u"Djibouti",
u"DJ-OB": u"Obock",
u"DJ-TA": u"Tadjoura",
u"DM-DM": u"Dominica",
u"DO-DN": u"Distrito National (Santo Domingo)",
u"DO-AZ": u"Azua",
u"DO-BR": u"Bahoruco",
u"DO-BH": u"Barahona",
u"DO-DA": u"Dajabón",
u"DO-DU": u"Duarte",
u"DO-SE": u"El Seibo",
u"DO-EP": u"La Estrelleta [Elías Piña]",
u"DO-HM": u"Hato Mayor",
u"DO-IN": u"Independencia",
u"DO-AL": u"La Altagracia",
u"DO-RO": u"La Romana",
u"DO-VE": u"La Vega",
u"DO-MT": u"María Trinidad Sánchez",
u"DO-MN": u"Monseñor Nouel",
u"DO-MC": u"Monte Cristi",
u"DO-MP": u"Monte Plata",
u"DO-PN": u"Pedernales",
u"DO-PR": u"Peravia",
u"DO-PP": u"Puerto Plata",
u"DO-SC": u"Salcedo",
u"DO-SM": u"Samaná",
u"DO-SZ": u"Sanchez Ramírez",
u"DO-CR": u"San Cristóbal",
u"DO-JU": u"San Juan",
u"DO-PM": u"San Pedro de Macorís",
u"DO-ST": u"Santiago",
u"DO-SR": u"Santiago Rodríguez",
u"DO-VA": u"Valverde",
u"TP-TP": u"East Timor",
u"EC-A": u"Azuay",
u"EC-B": u"Bolívar",
u"EC-F": u"Cañar",
u"EC-C": u"Carchi",
u"EC-X": u"Cotopaxi",
u"EC-H": u"Chimborazo",
u"EC-O": u"El Oro",
u"EC-E": u"Esmeraldas",
u"EC-W": u"Galápagos",
u"EC-G": u"Guayas",
u"EC-I": u"Imbabura",
u"EC-L": u"Loja",
u"EC-R": u"Los Ríos",
u"EC-M": u"Manabí",
u"EC-S": u"Morona-Santiago",
u"EC-N": u"Napo",
u"EC-Y": u"Pastaza",
u"EC-P": u"Pichincha",
u"EC-U": u"Sucumbíos",
u"EC-T": u"Tungurahua",
u"EC-Z": u"Zarnora-Chinchipe",
u"EG-DK": u"Ad Daqahlīyah",
u"EG-BA": u"Al Baḩr al Aḩmar",
u"EG-BH": u"Al Buḩayrah",
u"EG-FYM": u"Al Fayyūm",
u"EG-GH": u"Al Gharbīyah",
u"EG-ALX": u"Al Iskandarīyah",
u"EG-IS": u"Al Ismā‘īlīyah",
u"EG-GZ": u"Al Jīzah",
u"EG-MNF": u"Al Minūfīyah",
u"EG-MN": u"Al Minyā",
u"EG-C": u"Al Qāhirah",
u"EG-KB": u"Al Qalyūbīyah",
u"EG-WAD": u"Al Wādī al Jadīd",
u"EG-SHR": u"Ash Sharqīyah",
u"EG-SUZ": u"As Suways",
u"EG-ASN": u"Aswān",
u"EG-AST": u"Asyūţ",
u"EG-BNS": u"Banī Suwayf",
u"EG-PTS": u"Būr Sa‘īd",
u"EG-DT": u"Dumyāţ",
u"EG-JS": u"Janūb Sīnā'",
u"EG-KFS": u"Kafr ash Shaykh",
u"EG-MT": u"Maţrūḩ",
u"EG-KN": u"Qinā",
u"EG-SIN": u"Shamāl Sīnā'",
u"EG-SHG": u"Sūhāj",
u"SV-AH": u"Ahuachapán",
u"SV-CA": u"Cabañas",
u"SV-CU": u"Cuscatlán",
u"SV-CH": u"Chalatenango",
u"SV-LI": u"La Libertad",
u"SV-PA": u"La Paz",
u"SV-UN": u"La Unión",
u"SV-MO": u"Morazán",
u"SV-SM": u"San Miguel",
u"SV-SS": u"San Salvador",
u"SV-SA": u"Santa Ana",
u"SV-SV": u"San Vicente",
u"SV-SO": u"Sonsonate",
u"SV-SU": u"Usulután",
u"GQ-C": u"Región Continental",
u"GQ-CS": u"Centro Sur",
u"GQ-KN": u"Kie-Ntem",
u"GQ-LI": u"Litoral",
u"GQ-WN": u"Wele-Nzás",
u"GQ-I": u"Región Insular",
u"GQ-AN": u"Annobón",
u"GQ-BN": u"Bioko Norte",
u"GQ-BS": u"Bioko Sur",
u"ER-AG": u"Akele Guzai [Akalä Guzay]",
u"ER-AS": u"Asmara [Asmära]",
u"ER-BA": u"Barka",
u"ER-DE": u"Denkalia [Dänkali]",
u"ER-GS": u"Gash-Setit [Gaš enna Sätit]",
u"ER-HA": u"Hamasien [Hamasén]",
u"ER-SA": u"Sahel",
u"ER-SM": u"Semhar [Sämhar]",
u"ER-SN": u"Senhit [Sänhet]",
u"ER-SR": u"Seraye [Särayé]",
u"EE-37": u"Harjumaa",
u"EE-39": u"Hiiumaa",
u"EE-44": u"Ida-Virumaa",
u"EE-49": u"Jōgevamaa",
u"EE-51": u"Järvamaa",
u"EE-57": u"Läänemaa",
u"EE-59": u"Lääne-Virumaa",
u"EE-65": u"Pōlvamaa",
u"EE-67": u"Pärnumaa",
u"EE-70": u"Raplamaa",
u"EE-74": u"Saaremaa",
u"EE-78": u"Tartumaa",
u"EE-82": u"Valgamaa",
u"EE-84": u"Viljandimaa",
u"EE-86": u"Vōrumaa",
u"ET-AA": u"Addis Ababa [Addis Abeba]",
u"ET-AF": u"Afar",
u"ET-AM": u"Amara [Amhara]",
u"ET-BE": u"Benshangul-Gumaz [Bénishangul]",
u"ET-GA": u"Gambela Peoples [Gambéla]",
u"ET-HA": u"Harari People [Harer]",
u"ET-OR": u"Oromia [Oromo]",
u"ET-SO": u"Somali",
u"ET-SN": u"Southern Nations, Nationalities and Peoples",
u"ET-TI": u"Tigrai [Tegré]",
u"FK-FK": u"Falkland Islands (Malvinas)",
u"FO-FO": u"Faroe Islands",
u"FJ-C": u"Central",
u"FJ-E": u"Eastern",
u"FJ-N": u"Northern",
u"FJ-W": u"Western",
u"FJ-R": u"Rotuma",
u"FI-AL": u"Ahvenanmaan lääni",
u"FI-ES": u"Etelä-Suomen lääni",
u"FI-IS": u"Itä-Suomen lääni",
u"FI-LL": u"Lapin lääni",
u"FI-LS": u"Länsi-Suomen lääni",
u"FI-OL": u"Oulun lääni",
u"FR-A": u"Alsace",
u"FR-67": u"Bas-Rhin",
u"FR-68": u"Haut-Rhin",
u"FR-B": u"Aquitaine",
u"FR-79": u"Deux-Sèvres",
u"FR-24": u"Dordogne",
u"FR-33": u"Gironde",
u"FR-40": u"Landes",
u"FR-47": u"Lot-et-Garonne",
u"FR-64": u"Pyrénées-Atlantiques",
u"FR-C": u"Auvergne",
u"FR-03": u"Allier",
u"FR-15": u"Cantal",
u"FR-43": u"Haute-Loire",
u"FR-63": u"Puy-de-Dôme",
u"FR-P": u"Basse-Normandie",
u"FR-14": u"Calvados",
u"FR-50": u"Manche",
u"FR-61": u"Orne",
u"FR-D": u"Bourgogne",
u"FR-21": u"Côte-d'Or",
u"FR-58": u"Nièvre",
u"FR-71": u"Saône-et-Loire",
u"FR-89": u"Yonne",
u"FR-E": u"Bretagne",
u"FR-22": u"Cotes-d'Armor",
u"FR-29": u"Finistère",
u"FR-35": u"Ille-et-Vilaine",
u"FR-56": u"Morbihan",
u"FR-F": u"Centre",
u"FR-18": u"Cher",
u"FR-28": u"Eure-et-Loir",
u"FR-36": u"Indre",
u"FR-37": u"Indre-et-Loire",
u"FR-41": u"Loir-et-Cher",
u"FR-45": u"Loiret",
u"FR-G": u"Champagne-Ardenne",
u"FR-08": u"Ardennes",
u"FR-10": u"Aube",
u"FR-52": u"Haute-Marne",
u"FR-51": u"Marne",
u"FR-H": u"Corse",
u"FR-2A": u"Corse-du-Sud",
u"FR-2B": u"Haute-Corse",
u"FR-I": u"Franche-Comté",
u"FR-25": u"Doubs",
u"FR-70": u"Haute-Saône",
u"FR-39": u"Jura",
u"FR-90": u"Territoire de Belfort",
u"FR-Q": u"Haute-Normandie",
u"FR-27": u"Eure",
u"FR-76": u"Seine-Maritime",
u"FR-J": u"Île-de-France",
u"FR-91": u"Essonne",
u"FR-92": u"Hauts-de-Seine",
u"FR-75": u"Paris",
u"FR-77": u"Seine-et-Marne",
u"FR-93": u"Seine-Saint-Denis",
u"FR-94": u"Val-de-Marne",
u"FR-95": u"Val-d'Oise",
u"FR-78": u"Yvelines",
u"FR-K": u"Languedoc-Roussillon",
u"FR-11": u"Aude",
u"FR-30": u"Gard",
u"FR-34": u"Hérault",
u"FR-48": u"Lozère",
u"FR-66": u"Pyrénées-Orientales",
u"FR-L": u"Limousin",
u"FR-19": u"Corrèze",
u"FR-23": u"Creuse",
u"FR-87": u"Haute-Vienne",
u"FR-M": u"Lorraine",
u"FR-54": u"Meurthe-et-Moselle",
u"FR-55": u"Meuse",
u"FR-57": u"Moselle",
u"FR-88": u"Vosges",
u"FR-N": u"Midi-Pyrénées",
u"FR-09": u"Ariège",
u"FR-12": u"Aveyron",
u"FR-32": u"Gers",
u"FR-31": u"Haute-Garonne",
u"FR-65": u"Hautes-Pyrénées",
u"FR-46": u"Lot",
u"FR-81": u"Tarn",
u"FR-82": u"Tarn-et-Garonne",
u"FR-O": u"Nord-Pas-de-Calais",
u"FR-59": u"Nord",
u"FR-62": u"Pas-de-Calais",
u"FR-R": u"Pays de la Loire",
u"FR-44": u"Loire-Atlantique",
u"FR-49": u"Maine-et-Loire",
u"FR-53": u"Mayenne",
u"FR-72": u"Sarthe",
u"FR-85": u"Vendée",
u"FR-S": u"Picardie",
u"FR-02": u"Aisne",
u"FR-60": u"Oise",
u"FR-80": u"Somme",
u"FR-T": u"Poitou-Charentes",
u"FR-16": u"Charente",
u"FR-17": u"Charente-Maritime",
u"FR-86": u"Vienne",
u"FR-U": u"Provence-Alpes-Côte d'Azur",
u"FR-04": u"Alpes-de-Haute-Provence",
u"FR-06": u"Alpes-Maritimes",
u"FR-13": u"Bauches-du-Rhône",
u"FR-05": u"Hautes-Alpes",
u"FR-83": u"Var",
u"FR-84": u"Vaucluse",
u"FR-V": u"Rhône-Alpes",
u"FR-01": u"Ain",
u"FR-07": u"Ardèche",
u"FR-26": u"Drôme",
u"FR-74": u"Haute-Savoie",
u"FR-38": u"Isère",
u"FR-42": u"Loire",
u"FR-69": u"Rhône",
u"FR-73": u"Savoie",
u"FR-GP": u"Guadeloupe",
u"FR-GF": u"Guyane (francaise)",
u"FR-MQ": u"Martinique",
u"FR-RE": u"Réunion",
u"FR-YT": u"Mayotte",
u"FR-PM": u"Saint-Pierre-et-Miquelon",
u"FR-NC": u"Nouvelle-Calédonie",
u"FR-PF": u"Polynésie française",
u"FR-TF": u"Terres Australes",
u"FR-WF": u"Wallis et Futuna",
u"GF-GF": u"French Guiana",
u"PF-PF": u"French Polynesia",
u"TF-TF": u"French Southern Territories",
u"GA-1": u"Estuaire",
u"GA-2": u"Haut-Ogooué",
u"GA-3": u"Moyen-Ogooué",
u"GA-4": u"Ngounié",
u"GA-5": u"Nyanga",
u"GA-6": u"Ogooué-Ivindo",
u"GA-7": u"Ogooué-Lolo",
u"GA-8": u"Ogooué-Maritime",
u"GA-9": u"Woleu-Ntem",
u"GM-B": u"Banjul",
u"GM-L": u"Lower River",
u"GM-M": u"MacCarthy Island",
u"GM-N": u"North Bank",
u"GM-U": u"Upper River",
u"GM-W": u"Western",
u"GE-AB": u"Ap'khazet'is Avtonomiuri Respublika [Abkhazia]",
u"GE-AJ": u"Acharis Avtonomiuri Respublika [Ajaria]",
u"GE-BUS": u"Bat'umi",
u"GE-CHI": u"Chiat'ura",
u"GE-GAG": u"Gagra",
u"GE-GOR": u"Gori",
u"GE-KUT": u"K'ut'aisi",
u"GE-PTI": u"P'ot'i",
u"GE-RUS": u"Rust'avi",
u"GE-SUI": u"Sokhumi",
u"GE-TBS": u"T'bilisi",
u"GE-TQI": u"Tqibuli",
u"GE-TQV": u"Tqvarch'eli",
u"GE-TSQ": u"Tsqalmbo",
u"GE-ZUG": u"Zugdidi",
u"GE-01": u"Abashis Raioni",
u"GE-02": u"Adigenis Raioni",
u"GE-03": u"Akhalgoris Raioni",
u"GE-04": u"Akhalk'alak'is Raioni",
u"GE-05": u"Akhalts'ikhis Raioni",
u"GE-06": u"Akhmetis Raioni",
u"GE-07": u"Ambrolauris Raioni",
u"GE-08": u"Aspindzis Raioni",
u"GE-09": u"Baghdat'is Raioni",
u"GE-10": u"Bolnisis Raioni",
u"GE-11": u"Borjomis Raioni",
u"GE-12": u"Ch'khorotsqus Raioni",
u"GE-13": u"Ch'okhatauris Raioni",
u"GE-14": u"Dedop'listsqaros Raioni",
u"GE-15": u"Dmanisis Raioni",
u"GE-16": u"Dushet'is Raioni",
u"GE-17": u"Galis Raioni",
u"GE-18": u"Gardabnis Raioni",
u"GE-19": u"Goris Raioni",
u"GE-20": u"Gudaut'is Raioni",
u"GE-21": u"Gulrip'shis Raioni",
u"GE-22": u"Gurjaanis Raioni",
u"GE-23": u"Javis Raioni",
u"GE-24": u"K'arelis Raioni",
u"GE-25": u"Kaspis Raioni",
u"GE-26": u"K'edis Raioni",
u"GE-27": u"Kharagaulis Raioni",
u"GE-28": u"Khashuris Raioni",
u"GE-29": u"Khelvach'auris Raioni",
u"GE-30": u"Khobis Raioni",
u"GE-31": u"Khonis Raioni",
u"GE-32": u"Khulos Raioni",
u"GE-33": u"K'obuletis Raioni",
u"GE-34": u"Lagodekhis Raioni",
u"GE-35": u"Lanch'khut'is Raioni",
u"GE-36": u"Lentekhis Raioni",
u"GE-37": u"Marneulis Raioni",
u"GE-38": u"Martvilis Raioni",
u"GE-39": u"Mestiis Raioni",
u"GE-40": u"Mts'khet'is Raioni",
u"GE-41": u"Ninotsmindis Raioni",
u"GE-42": u"Och'amch'iris Raioni",
u"GE-43": u"Onis Raioni",
u"GE-44": u"Ozurget'is Raioni",
u"GE-45": u"Qazbegis Raioni",
u"GE-46": u"Qvarlis Raioni",
u"GE-47": u"Sach'kheris Raioni",
u"GE-48": u"Sagarejos Raioni",
u"GE-49": u"Samtrediis Raioni",
u"GE-50": u"Senakis Raioni",
u"GE-51": u"Shuakhevis Raioni",
u"GE-52": u"Sighnaghis Raioni",
u"GE-53": u"Sokhumis Raioni",
u"GE-54": u"T'elavis Raioni",
u"GE-55": u"T'erjolis Raioni",
u"GE-56": u"T'et'ritsqaros Raioni",
u"GE-57": u"T'ianet'is Raioni",
u"GE-58": u"Ts'ageris Raioni",
u"GE-59": u"Tsalenjikhis Raioni",
u"GE-60": u"Tsalkis Raioni",
u"GE-61": u"Vanis Raioni",
u"GE-62": u"Zestap'onis Raioni",
u"GE-63": u"Zugdidis Raioni",
u"DE-BW": u"Baden-Württemberg",
u"DE-BY": u"Bayern",
u"DE-BE": u"Berlin",
u"DE-BB": u"Brandenburg",
u"DE-HB": u"Bremen",
u"DE-HH": u"Hamburg",
u"DE-HE": u"Hessen",
u"DE-MV": u"Mecklenburg-Vorpommern",
u"DE-NI": u"Niedersachsen",
u"DE-NW": u"Nordrhein-Westfalen",
u"DE-RP": u"Rheinland-Pfalz",
u"DE-SL": u"Saarland",
u"DE-SN": u"Sachsen",
u"DE-ST": u"Sachsen-Anhalt",
u"DE-SH": u"Schleswig-Holstein",
u"DE-TH": u"Thüringen",
u"GH-AH": u"Ashanti",
u"GH-BA": u"Brong-Ahafo",
u"GH-CP": u"Central",
u"GH-EP": u"Eastern",
u"GH-AA": u"Greater Accra",
u"GH-NP": u"Northern",
u"GH-UE": u"Upper East",
u"GH-UW": u"Upper West",
u"GH-TV": u"Volta",
u"GH-WP": u"Western",
u"GI-GI": u"Gibraltar",
u"GB-CHA": u"Channel Islands",
u"GB-GSY": u"Guernsey [Guernesey]",
u"GB-JSY": u"Jersey",
u"GB-ENG": u"England",
u"GB-BDG": u"Barking and Dagenham",
u"GB-BNE": u"Barnet",
u"GB-BNS": u"Barnsley",
u"GB-BAS": u"Bath and North East Somerset",
u"GB-BDF": u"Bedfordshire",
u"GB-BEX": u"Bexley",
u"GB-BIR": u"Birmingham (City of)",
u"GB-BBD": u"Blackburn with Darwen",
u"GB-BPL": u"Blackpool",
u"GB-BOL": u"Bolton",
u"GB-BMH": u"Bournemouth",
u"GB-BRC": u"Bracknell Forest",
u"GB-BRD": u"Bradford (City of)",
u"GB-BEN": u"Brent",
u"GB-BNH": u"Brighton and Hove",
u"GB-BST": u"Bristol, City of",
u"GB-BRY": u"Bromley",
u"GB-BKM": u"Buckinghamshire",
u"GB-BUR": u"Bury",
u"GB-CLD": u"Calderdale",
u"GB-CAM": u"Cambridgeshire",
u"GB-CMD": u"Camden",
u"GB-CHS": u"Cheshire",
u"GB-CON": u"Cornwall",
u"GB-COV": u"Coventry (City of)",
u"GB-CRY": u"Croydon",
u"GB-CMA": u"Cumbria",
u"GB-DAL": u"Darlington",
u"GB-DER": u"Derby (City of)",
u"GB-DBY": u"Derbyshire",
u"GB-DEV": u"Devon",
u"GB-DNC": u"Doncaster",
u"GB-DOR": u"Dorset",
u"GB-DUD": u"Dudley",
u"GB-DUR": u"Durharn",
u"GB-EAL": u"Ealing",
u"GB-ERY": u"East Riding of Yorkshire",
u"GB-ESX": u"East Sussex",
u"GB-ENF": u"Enfield",
u"GB-ESS": u"Essex",
u"GB-GAT": u"Gateshead",
u"GB-GLS": u"Gloucestershire",
u"GB-GRE": u"Greenwich",
u"GB-HCK": u"Hackney",
u"GB-HAL": u"Haiton",
u"GB-HMF": u"Hammersmith and Fulham",
u"GB-HAM": u"Hampshire",
u"GB-HRY": u"Haringey",
u"GB-HRW": u"Harrow",
u"GB-HPL": u"Hartlepool",
u"GB-HAV": u"Havering",
u"GB-HEF": u"Herefordshire, County of",
u"GB-HRT": u"Hertfordshire",
u"GB-HIL": u"Hillingdon",
u"GB-HNS": u"Hounslow",
u"GB-IOW": u"Isle of Wight",
u"GB-IOS": u"Isles of Scilly",
u"GB-ISL": u"Islington",
u"GB-KEC": u"Kensington and Chelsea",
u"GB-KEN": u"Kent",
u"GB-KHL": u"Kingston upon Hull, City of",
u"GB-KTT": u"Kingston upon Thames",
u"GB-KIR": u"Kirklees",
u"GB-KWL": u"Knowsley",
u"GB-LBH": u"Lambeth",
u"GB-LAN": u"Lancashire",
u"GB-LDS": u"Leeds (City of)",
u"GB-LCE": u"Leitester (City of)",
u"GB-LEC": u"Leicestershire",
u"GB-LEW": u"Lewisham",
u"GB-LIN": u"Lincolnshire",
u"GB-LIV": u"Liverpool (City of)",
u"GB-LND": u"London, City of",
u"GB-LUT": u"Luton",
u"GB-MAN": u"Manchester (City of)",
u"GB-MDW": u"Medway",
u"GB-MRT": u"Merton",
u"GB-MDB": u"Middlesbrough",
u"GB-MIK": u"Milton Keynes",
u"GB-NET": u"Newcastle upon Tyne (City of)",
u"GB-NWM": u"Newham",
u"GB-NFK": u"Norfolk",
u"GB-NEL": u"North East Lincolnshire",
u"GB-NLN": u"North Lincolnshire",
u"GB-NSM": u"North Somerset",
u"GB-NTY": u"North Tyneside",
u"GB-NYK": u"North Yorkshire",
u"GB-NTH": u"Northamptonshire",
u"GB-NBL": u"Northumberland",
u"GB-NGM": u"Nottingham (City of)",
u"GB-NTT": u"Nottinghamshire",
u"GB-OLD": u"Oldham",
u"GB-OXF": u"Oxfordshire",
u"GB-PTE": u"Peterborough",
u"GB-PLY": u"Plymouth (City of)",
u"GB-POL": u"Poole",
u"GB-POR": u"Portsmouth (City of)",
u"GB-RDG": u"Reading",
u"GB-RDB": u"Redbridge",
u"GB-RCC": u"Redcar and Cleveland",
u"GB-RIC": u"Richmond upon Thames",
u"GB-RCH": u"Rochdale",
u"GB-ROT": u"Rotherharn",
u"GB-RUT": u"Rutland",
u"GB-SHN": u"St. Helens",
u"GB-SLF": u"Salford (City of)",
u"GB-SAW": u"Sandweil",
u"GB-SFT": u"Sefton",
u"GB-SHF": u"Sheffield (City of)",
u"GB-SHR": u"Shropshire",
u"GB-SLG": u"Slough",
u"GB-SOL": u"Solihull",
u"GB-SOM": u"Somerset",
u"GB-SGC": u"South Gloucestershire",
u"GB-STY": u"South Tyneside",
u"GB-STH": u"Southampton (City of)",
u"GB-SOS": u"Southend-on-Sea",
u"GB-SWK": u"Southwark",
u"GB-STS": u"Staffordshire",
u"GB-SKP": u"Stockport",
u"GB-STT": u"Stockton-On-Tees",
u"GB-STE": u"Stoke-on-Trent (City of)",
u"GB-SFK": u"Suffolk",
u"GB-SND": u"Sunderland (City of)",
u"GB-SRY": u"Surrey",
u"GB-STN": u"Sutton",
u"GB-SWD": u"Swindon",
u"GB-TAM": u"Tameside",
u"GB-TFW": u"Telford and Wrekin",
u"GB-THR": u"Thurrock",
u"GB-TOB": u"Torbay",
u"GB-TWH": u"Tower Hamlets",
u"GB-TRF": u"Trafford",
u"GB-WKF": u"Wakefield (City of)",
u"GB-WLL": u"Walsall",
u"GB-WFT": u"Waltham Forest",
u"GB-WND": u"Wandsworth",
u"GB-WRT": u"Warrington",
u"GB-WAR": u"Warwickshire",
u"GB-WBK": u"West Berkshire",
u"GB-WSX": u"West Sussex",
u"GB-WSM": u"Westminster (City of)",
u"GB-WGN": u"Wigan",
u"GB-WIL": u"Wiltshire",
u"GB-WNM": u"Windsor and Maidenhead",
u"GB-WRL": u"Wirral",
u"GB-WOK": u"Wokingham",
u"GB-WLV": u"Wolverhampton",
u"GB-WOR": u"Worcestershire",
u"GB-YOR": u"York (City of)",
u"GB-IOM": u"Isle of Man",
u"GB-NIR": u"Northern Ireland",
u"GB-ANT": u"Antrim",
u"GB-ARD": u"Ards",
u"GB-ARM": u"Armagh",
u"GB-BLA": u"Ballymena",
u"GB-BLY": u"Ballymoney",
u"GB-BNB": u"Banbridge",
u"GB-BFS": u"Belfast (City of)",
u"GB-CKF": u"Carrickfergus",
u"GB-CSR": u"Castlereagh",
u"GB-CLR": u"Coleraine",
u"GB-CKT": u"Cookstown",
u"GB-CGV": u"Craigavon",
u"GB-DRY": u"Derry (City of)",
u"GB-DOW": u"Down",
u"GB-DGN": u"Dungannon",
u"GB-FER": u"Fermanagh",
u"GB-LRN": u"Larne",
u"GB-LMV": u"Limavady",
u"GB-LSB": u"Lisburn",
u"GB-MFT": u"Magherafelt",
u"GB-MYL": u"Moyle",
u"GB-NYM": u"Newry and Mourne",
u"GB-NTA": u"Newtownabbey",
u"GB-NDN": u"North Down",
u"GB-OMH": u"Omagh",
u"GB-STB": u"Strabane",
u"GB-SCT": u"Scotland",
u"GB-ABE": u"Aberdeen City",
u"GB-ABD": u"Aberdeenshire",
u"GB-ANS": u"Angus",
u"GB-AGB": u"Argyll and Bute",
u"GB-CLK": u"Clackmannanshire",
u"GB-DGY": u"Dumfries and Galloway",
u"GB-DND": u"Dundee City",
u"GB-EAY": u"East Ayrshire",
u"GB-EDU": u"East Dunbartonshire",
u"GB-ELN": u"East Lothian",
u"GB-ERW": u"East Renfrewshire",
u"GB-EDH": u"Edinburgh, City of",
u"GB-ELS": u"Eilean Siar",
u"GB-FAL": u"Falkirk",
u"GB-FIF": u"Fife",
u"GB-GLG": u"Glasgow City",
u"GB-HLD": u"Highland",
u"GB-IVC": u"Inverclyde",
u"GB-MLN": u"Midlothian",
u"GB-MRY": u"Moray",
u"GB-NAY": u"North Ayrshire",
u"GB-NLK": u"North Lanarkshire",
u"GB-ORK": u"Orkney Islands",
u"GB-PKN": u"Perth and Kinross",
u"GB-RFW": u"Renfrewshire",
u"GB-SCB": u"Scottish Borders, The",
u"GB-ZET": u"Shetland Islands",
u"GB-SAY": u"South Ayrshire",
u"GB-SLK": u"South Lanarkshire",
u"GB-STG": u"Stirling",
u"GB-WDU": u"West Dunbartonshire",
u"GB-WLN": u"West Lothian",
u"GB-WLS": u"Wales [Cymru]",
u"GB-BGW": u"Blaenau Gwent",
u"GB-BGE": u"Bridgend [Pen-y-bont ar Ogwr GB-POG]",
u"GB-CAY": u"Caerphilly [Caerffili GB-CAF]",
u"GB-CRF": u"Cardiff (City of) [Caerdydd GB-CRD]",
u"GB-CMN": u"Carmarthenshire [Sir Gaerfyrddin GB-GFY]",
u"GB-CGN": u"Ceredigion [Sir Ceredigion]",
u"GB-CWY": u"Conwy",
u"GB-DEN": u"Denbighshire [Sir Ddinbych GB-DDB]",
u"GB-FLN": u"Flintshire [Sir y Fflint GB-FFL]",
u"GB-GWN": u"Gwynedd",
u"GB-AGY": u"Isle of Anglesey [Sir Ynys Man GB-YNM]",
u"GB-MTY": u"Merthyr Tydfil [Merthyr Tudful GB-MTU]",
u"GB-MON": u"Monmouthshire [Sir Fynwy GB-FYN]",
u"GB-NTL": u"Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]",
u"GB-NWP": u"Newport [Casnewydd GB-CNW]",
u"GB-PEM": u"Pembrokeshire [Sir Benfro CB-BNF]",
u"GB-POW": u"Powys",
u"GB-RCT": u"Rhondda, Cynon, Taff [Rhondda, Cynon, Taf]",
u"GB-SWA": u"Swansea (City of) [Abertawe GB-ATA]",
u"GB-TOF": u"Torfaen [Tor-faen]",
u"GB-VGL": u"Vale of Glamorgan, The [Bro Morgannwg GB-BMG]",
u"GB-WRX": u"Wrexham [Wrecsam GB-WRC]",
u"GR-I": u"Anatoliki Makedonia kai Thraki",
u"GR-52": u"Drama",
u"GR-71": u"Evros",
u"GR-55": u"Kavalla",
u"GR-73": u"Rodopi",
u"GR-72": u"Xanthi",
u"GR-IX": u"Attiki",
u"GR-A1": u"Attiki",
u"GR-VII": u"Dytiki Ellada",
u"GR-13": u"Achaïa",
u"GR-01": u"Aitolia-Akarnania",
u"GR-14": u"Ileia",
u"GR-III": u"Dytiki Makedonia",
u"GR-63": u"Florina",
u"GR-51": u"Grevena",
u"GR-56": u"Kastoria",
u"GR-58": u"Kozani",
u"GR-VI": u"Ionioi Nisoi",
u"GR-23": u"Kefallinia",
u"GR-22": u"Kerkyra",
u"GR-24": u"Lefkas",
u"GR-21": u"Zakynthos",
u"GR-IV": u"Ipeiros",
u"GR-31": u"Arta",
u"GR-33": u"Ioannina",
u"GR-34": u"Preveza",
u"GR-32": u"Thesprotia",
u"GR-II": u"Kentriki Makedonia",
u"GR-64": u"Chalkidiki",
u"GR-53": u"Imathia",
u"GR-57": u"Kilkis",
u"GR-59": u"Pella",
u"GR-61": u"Pieria",
u"GR-62": u"Serrai",
u"GR-54": u"Thessaloniki",
u"GR-XIII": u"Kriti",
u"GR-94": u"Chania",
u"GR-91": u"Irakleion",
u"GR-92": u"Lasithion",
u"GR-93": u"Rethymnon",
u"GR-XII": u"Notio Aigaio",
u"GR-81": u"Dodekanisos",
u"GR-82": u"Kyklades",
u"GR-X": u"Peloponnisos",
u"GR-11": u"Argolis",
u"GR-12": u"Arkadia",
u"GR-15": u"Korinthia",
u"GR-16": u"Lakonia",
u"GR-17": u"Messinia",
u"GR-VIII": u"Sterea Ellada",
u"GR-05": u"Evrytania",
u"GR-04": u"Evvoia",
u"GR-07": u"Fokis",
u"GR-06": u"Fthiotis",
u"GR-03": u"Voiotia",
u"GR-V": u"Thessalia",
u"GR-41": u"Karditsa",
u"GR-42": u"Larisa",
u"GR-43": u"Magnisia",
u"GR-44": u"Trikala",
u"GR-XI": u"Voreio Aigaio",
u"GR-85": u"Chios",
u"GR-83": u"Lesvos",
u"GR-84": u"Samos",
u"GL-GL": u"Greenland",
u"GD-GD": u"Grenada",
u"GP-GP": u"Guadeloupe",
u"GU-GU": u"Guam",
u"GT-AV": u"Alta Verapaz",
u"GT-BV": u"Baja Verapaz",
u"GT-CM": u"Chimaltenango",
u"GT-CQ": u"Chiquimula",
u"GT-PR": u"El Progreso",
u"GT-ES": u"Escuintla",
u"GT-GU": u"Guatemala",
u"GT-HU": u"Huehuetenango",
u"GT-IZ": u"Izabal",
u"GT-JA": u"Jalapa",
u"GT-JU": u"Jutiapa",
u"GT-PE": u"Petén",
u"GT-QZ": u"Quezaltenango",
u"GT-QC": u"Quiché",
u"GT-RE": u"Retalhuleu",
u"GT-SA": u"Sacatepéquez",
u"GT-SM": u"San Marcos",
u"GT-SR": u"Santa Rosa",
u"GT-SO": u"Sololá",
u"GT-SU": u"Suchitepéquez",
u"GT-TO": u"Totonicapán",
u"GT-ZA": u"Zacapa",
u"GN-B": u"Bake, Gouvernorat de",
u"GN-BF": u"Boffa",
u"GN-BK": u"Boké",
u"GN-FR": u"Fria",
u"GN-GA": u"Gaoual",
u"GN-KD": u"Koundara",
u"GN-C": u"Conakry, Gouvernorat de",
u"GN-F": u"Faranah, Gouvernorat de",
u"GN-DB": u"Dabola",
u"GN-DI": u"Dinguiraye",
u"GN-FA": u"Faranah",
u"GN-KS": u"Kissidougou",
u"GN-K": u"Kankan, Gouvernorat de",
u"GN-KA": u"Kankan",
u"GN-KE": u"Kérouané",
u"GN-KO": u"Kouroussa",
u"GN-MD": u"Mandiana",
u"GN-SI": u"Siguiri",
u"GN-D": u"Kindia, Gouvernorat de",
u"GN-CO": u"Coyah",
u"GN-DU": u"Dubréka",
u"GN-FO": u"Forécariah",
u"GN-KD": u"Kindia",
u"GN-TE": u"Télimélé",
u"GN-L": u"Labé, Gouvernorat de",
u"GN-KB": u"Koubia",
u"GN-LA": u"Labé",
u"GN-LE": u"Lélouma",
u"GN-ML": u"Mali",
u"GN-TO": u"Tougué",
u"GN-M": u"Mamou, Gouvernorat de",
u"GN-DL": u"Dalaba",
u"GN-MM": u"Mamou",
u"GN-PI": u"Pita",
u"GN-N": u"Nzérékoré, Gouvernorat de",
u"GN-BE": u"Beyla",
u"GN-GU": u"Guékédou",
u"GN-LO": u"Lola",
u"GN-MC": u"Macenta",
u"GN-NZ": u"Nzérékoré",
u"GN-YO": u"Yomou",
u"GW-BS": u"Bissau",
u"GW-BA": u"Bafatá",
u"GW-BM": u"Biombo",
u"GW-BL": u"Bolama",
u"GW-CA": u"Cacheu",
u"GW-GA": u"Gabú",
u"GW-OI": u"Oio",
u"GW-QU": u"Quinara",
u"GY-BA": u"Barima-Waini",
u"GY-CU": u"Cuyuni-Mazaruni",
u"GY-DE": u"Demerara-Mahaica",
u"GY-EB": u"East Berbice-Corentyne",
u"GY-ES": u"Essequibo Islands-West Demerara",
u"GY-MA": u"Mahaica-Berbice",
u"GY-PM": u"Pomeroon-Supenaam",
u"GY-PT": u"Potaro-Siparuni",
u"GY-UD": u"Upper Demerara-Berbice",
u"GY-UT": u"Upper Takutu-Upper Essequibo",
u"HT-AR": u"Artibonite",
u"HT-CE": u"Centre",
u"HT-GA": u"Grande-Anse",
u"HT-ND": u"Nord",
u"HT-NE": u"Nord-Est",
u"HT-NO": u"Nord-Ouest",
u"HT-OU": u"Ouest",
u"HT-SD": u"Sud",
u"HT-SE": u"Sud-Est",
u"HM-HM": u"Heard & McDonald Islands",
u"VA-VA": u"Vatican City (Holy See)",
u"HN-AT": u"Atlántida",
u"HN-CL": u"Colón",
u"HN-CM": u"Comayagua",
u"HN-CP": u"Copán",
u"HN-CR": u"Cortés",
u"HN-CH": u"Choluteca",
u"HN-EP": u"El Paraíso",
u"HN-FM": u"Francisco Morazán",
u"HN-GD": u"Gracias a Dios",
u"HN-IN": u"Intibucá",
u"HN-IB": u"Islas de la Bahía",
u"HN-LP": u"La Paz",
u"HN-LE": u"Lempira",
u"HN-OC": u"Ocotepeque",
u"HN-OL": u"Olancho",
u"HN-SB": u"Santa Bárbara",
u"HN-VA": u"Valle",
u"HN-YO": u"Yoro",
u"HK-HK": u"Hong Kong",
u"HU-BU": u"Budapest",
u"HU-BK": u"Bács-Kiskun",
u"HU-BA": u"Baranya",
u"HU-BE": u"Békés",
u"HU-BZ": u"Borsod-Abaúj-Zemplén",
u"HU-CS": u"Csongrád",
u"HU-FE": u"Fejér",
u"HU-GS": u"Gyór-Moson-Sopron",
u"HU-HB": u"Hajdú-Bihar",
u"HU-HE": u"Heves",
u"HU-JN": u"Jasz-Nagykun-Szolnok",
u"HU-KE": u"Komárom-Esztergom",
u"HU-NO": u"Nógrád",
u"HU-PE": u"Pest",
u"HU-SO": u"Somogy",
u"HU-SZ": u"Szabolcs-Szatmár-Bereg",
u"HU-TO": u"Tolna",
u"HU-VA": u"Vas",
u"HU-VE": u"Veszprém",
u"HU-ZA": u"Zala",
u"HU-BC": u"Békéscsaba",
u"HU-DE": u"Debrecen",
u"HU-DU": u"Dunaújváros",
u"HU-EG": u"Eger",
u"HU-GY": u"Gyór",
u"HU-HV": u"Hódmezóvásárhely",
u"HU-KV": u"Kaposvár",
u"HU-KM": u"Kecskemét",
u"HU-MI": u"Miskolc",
u"HU-NK": u"Nagykanizsa",
u"HU-NY": u"Nyíregyháza",
u"HU-PS": u"Pécs",
u"HU-ST": u"Salgótarján",
u"HU-SN": u"Sopron",
u"HU-SD": u"Szeged",
u"HU-SF": u"Székesfehérvár",
u"HU-SS": u"Szekszárd",
u"HU-SK": u"Szolnok",
u"HU-SH": u"Szombathely",
u"HU-TB": u"Tatabánya",
u"HU-VM": u"Veszprém",
u"HU-ZE": u"Zalaegerszeg",
u"IS-7": u"Austurland",
u"IS-1": u"Höfudborgarsvædi utan Reykjavíkur",
u"IS-6": u"Nordurland eystra",
u"IS-5": u"Nordurland vestra",
u"IS-0": u"Reykjavīk",
u"IS-8": u"Sudurland",
u"IS-2": u"Sudurnes",
u"IS-4": u"Vestfirdir",
u"IS-3": u"Vesturland",
u"IN-AP": u"Andhra Pradesh",
u"IN-AR": u"Arunachal Pradesh",
u"IN-AS": u"Assam",
u"IN-BR": u"Bihar",
u"IN-GA": u"Goa",
u"IN-GJ": u"Gujarat",
u"IN-HR": u"Haryana",
u"IN-HP": u"Himachal Pradesh",
u"IN-JK": u"Jammu and Kashmir",
u"IN-KA": u"Karnataka",
u"IN-KL": u"Kerala",
u"IN-MP": u"Madhya Pradesh",
u"IN-MH": u"Maharashtra",
u"IN-MN": u"Manipur",
u"IN-ML": u"Meghalaya",
u"IN-MZ": u"Mizoram",
u"IN-NL": u"Nagaland",
u"IN-OR": u"Orissa",
u"IN-PB": u"Punjab",
u"IN-RJ": u"Rajasthan",
u"IN-SK": u"Sikkim",
u"IN-TN": u"Tamil Nadu",
u"IN-TR": u"Tripura",
u"IN-UP": u"Uttar Pradesh",
u"IN-WB": u"West Bengal",
u"IN-AN": u"Andaman and Nicobar Islands",
u"IN-CH": u"Chandigarh",
u"IN-DN": u"Dadra and Nagar Haveli",
u"IN-DD": u"Daman and Diu",
u"IN-DL": u"Delhi",
u"IN-LD": u"Lakshadweep",
u"IN-PY": u"Pondicherry",
u"ID-IJU": u"Irian Jaya",
u"ID-IJ": u"Irian Jaya",
u"ID-JWU": u"Jawa",
u"ID-JB": u"Jawa Barat",
u"ID-JT": u"Jawa Tengah",
u"ID-JI": u"Jawa Timur",
u"ID-JK": u"Jakarta Raya",
u"ID-YO": u"Yogyakarta",
u"ID-KAU": u"Kalimantan",
u"ID-KB": u"Kalimantan Barat",
u"ID-KS": u"Kalimantan Selatan",
u"ID-KT": u"Kalimantan Tengah",
u"ID-KI": u"Kalimantan Timur",
u"ID-MAU": u"Maluku",
u"ID-MA": u"Maluku",
u"ID-NUU": u"Nusa Tenggara",
u"ID-BA": u"Bali",
u"ID-NB": u"Nusa Tenggara Barat",
u"ID-NT": u"Nusa Tenggara Timur",
u"ID-TT": u"Timor Timur",
u"ID-SLU": u"Sulawesi",
u"ID-SN": u"Sulawesi Selatan",
u"ID-ST": u"Sulawesi Tengah",
u"ID-SG": u"Sulawesi Tenggara",
u"ID-SA": u"Sulawesi Utara",
u"ID-SMU": u"Sumatera",
u"ID-BE": u"Bengkulu",
u"ID-JA": u"Jambi",
u"ID-LA": u"Lampung",
u"ID-RI": u"Riau",
u"ID-SB": u"Sumatera Barat",
u"ID-SS": u"Sumatera Selatan",
u"ID-SU": u"Sumatera Utara",
u"ID-AC": u"Aceh",
u"IR-03": u"Ardabīl",
u"IR-02": u"Āzarbāyjān-e-Gharbī",
u"IR-01": u"Āzarbāyjān-e-Sharqī",
u"IR-06": u"Būshehr",
u"IR-08": u"Chahār Maḩāll vā Bakhtīārī",
u"IR-04": u"Eşfahān",
u"IR-14": u"Fārs",
u"IR-19": u"Gīlān",
u"IR-24": u"Hamadān",
u"IR-23": u"Hormozgān",
u"IR-05": u"Īlām",
u"IR-15": u"Kermān",
u"IR-17": u"Kermānshāhān",
u"IR-09": u"Khorāsān",
u"IR-10": u"Khūzestān",
u"IR-18": u"Kohkīlūyeh va Būyer Aḩmadī",
u"IR-16": u"Kordestān",
u"IR-20": u"Lorestān",
u"IR-22": u"Markazī",
u"IR-21": u"Māzandarān",
u"IR-26": u"Qom",
u"IR-12": u"Semnān",
u"IR-13": u"Sīstān va Balūchestān",
u"IR-07": u"Tehrān",
u"IR-25": u"Yazd",
u"IR-11": u"Zanjān",
u"IQ-AN": u"Al Anbār",
u"IQ-BA": u"Al Başrah",
u"IQ-MU": u"Al Muthanná",
u"IQ-QA": u"Al Qādisīyah",
u"IQ-NA": u"An Najaf",
u"IQ-AR": u"Arbīl",
u"IQ-SU": u"As Sulaymānīyah",
u"IQ-TS": u"At Ta'mīm",
u"IQ-BB": u"Bābil",
u"IQ-BG": u"Baghdād",
u"IQ-DA": u"Dahūk",
u"IQ-DQ": u"Dhī Qār",
u"IQ-DI": u"Diyālá",
u"IQ-KA": u"Karbalā'",
u"IQ-MA": u"Maysān",
u"IQ-NI": u"Nīnawá",
u"IQ-SD": u"Şalāḩ ad Dīn",
u"IQ-WA": u"Wāsiţ",
u"IE-CP": u"Connaught (Connacht)",
u"IE-G": u"Galway (Gaillimh)",
u"IE-LM": u"Leitrim (Liatroim)",
u"IE-MO": u"Mayo (Maigh Eo)",
u"IE-RN": u"Roscommon (Ros Comáin)",
u"IE-SO": u"Sligo (Sligeach)",
u"IE-LP": u"Leinster (Laighin)",
u"IE-CW": u"Carlow (Ceatharlach)",
u"IE-D": u"Dublin (Baile Átha Cliath)",
u"IE-KE": u"Kildare (Cill Dara)",
u"IE-KK": u"Kilkenny (Cill Chainnigh)",
u"IE-LS": u"Laois (Laois)",
u"IE-LD": u"Longford (An Longfort)",
u"IE-LH": u"Louth (Lú)",
u"IE-MH": u"Meath (An Mhí)",
u"IE-OY": u"Offaly (Uíbh Fhailí)",
u"IE-WH": u"Westmeath (An Iarmhí)",
u"IE-WX": u"Wexford (Loch Garman)",
u"IE-WW": u"Wicklow (Cill Mhantáin)",
u"IE-M": u"Munster (An Mhumhain)",
u"IE-UP": u"Ulster (Ulaidh)",
u"IE-CN": u"Cavan (An Cabhán)",
u"IE-DL": u"Donegal (Dún na nGall)",
u"IE-MN": u"Monaghan (Muineachán)",
u"IL-D": u"HaDarom (El Janūbī)",
u"IL-M": u"HaMerkaz (El Awsat)",
u"IL-2": u"HaZafon (Esh Shamālī)",
u"IL-HA": u"Hefa (Heifā)",
u"IL-TA": u"Tel-Aviv (Tell Abīb)",
u"IL-JM": u"Yerushalayim (Al Quds)",
u"IT-65": u"Abruzzo",
u"IT-CH": u"Chieti",
u"IT-AQ": u"L'Aquila",
u"IT-PE": u"Pescara",
u"IT-TE": u"Teramo",
u"IT-77": u"Basilicata",
u"IT-MT": u"Matera",
u"IT-PZ": u"Potenza",
u"IT-78": u"Calabria",
u"IT-CZ": u"Catanzaro",
u"IT-CS": u"Cosenza",
u"IT-KR": u"Crotone",
u"IT-RC": u"Reggio Calabria",
u"IT-W": u"Vibo Valentia",
u"IT-72": u"Campania",
u"IT-AV": u"Avellino",
u"IT-BN": u"Benevento",
u"IT-CE": u"Caserta",
u"IT-NA": u"Napoli",
u"IT-SA": u"Salerno",
u"IT-45": u"Emilia-Romagna",
u"IT-BO": u"Bologna",
u"IT-FE": u"Ferrara",
u"IT-FO": u"Forlì",
u"IT-MO": u"Modena",
u"IT-PR": u"Parma",
u"IT-PC": u"Piacenza",
u"IT-RA": u"Ravenna",
u"IT-RE": u"Reggio Emilia",
u"IT-RN": u"Rimini",
u"IT-36": u"Friuli-Venezia Giulia",
u"IT-GO": u"Gorizia",
u"IT-PN": u"Pordenone",
u"IT-TS": u"Trieste",
u"IT-UD": u"Udine",
u"IT-62": u"Lazio",
u"IT-FR": u"Frosinone",
u"IT-LT": u"Latina",
u"IT-RI": u"Rieti",
u"IT-RM": u"Roma",
u"IT-VT": u"Viterbo",
u"IT-42": u"Liguria",
u"IT-GE": u"Genova",
u"IT-IM": u"Imperia",
u"IT-SP": u"La Spezia",
u"IT-SV": u"Savona",
u"IT-25": u"Lombardia",
u"IT-BG": u"Bergamo",
u"IT-BS": u"Brescia",
u"IT-CO": u"Como",
u"IT-CR": u"Cremona",
u"IT-LC": u"Lecco",
u"IT-LO": u"Lodi",
u"IT-MN": u"Mantova",
u"IT-MI": u"Milano",
u"IT-PV": u"Pavia",
u"IT-SO": u"Sondrio",
u"IT-VA": u"Varese",
u"IT-57": u"Marche",
u"IT-AN": u"Ancona",
u"IT-AP": u"Ascoli Piceno",
u"IT-MC": u"Macerata",
u"IT-PS": u"Pesaro",
u"IT-67": u"Molise",
u"IT-CB": u"Campobasso",
u"IT-IS": u"Isernia",
u"IT-21": u"Piemonte",
u"IT-AL": u"Alessandria",
u"IT-AT": u"Asti",
u"IT-BI": u"Biella",
u"IT-CN": u"Cuneo",
u"IT-NO": u"Novara",
u"IT-TO": u"Torino",
u"IT-VB": u"Verbano-Cusio-Ossola",
u"IT-VC": u"Vercelli",
u"IT-75": u"Puglia",
u"IT-BA": u"Bari",
u"IT-BR": u"Brindisi",
u"IT-FG": u"Foggia",
u"IT-LE": u"Lecce",
u"IT-TA": u"Taranto",
u"IT-88": u"Sardegna",
u"IT-CA": u"Cagliari",
u"IT-NU": u"Nuoro",
u"IT-OR": u"Oristano",
u"IT-SS": u"Sassari",
u"IT-82": u"Sicilia",
u"IT-AG": u"Agrigento",
u"IT-CL": u"Caltanissetta",
u"IT-CT": u"Catania",
u"IT-EN": u"Enna",
u"IT-ME": u"Mesaina",
u"IT-PA": u"Palermo",
u"IT-RG": u"Ragusa",
u"IT-SR": u"Siracusa",
u"IT-TP": u"Trapani",
u"IT-52": u"Toscana",
u"IT-AR": u"Arezzo",
u"IT-FI": u"Firenze",
u"IT-GR": u"Grosseto",
u"IT-LI": u"Livorno",
u"IT-LU": u"Lucca",
u"IT-MS": u"Massa",
u"IT-PI": u"Pisa",
u"IT-PT": u"Pistoia",
u"IT-PO": u"Prato",
u"IT-SI": u"Siena",
u"IT-32": u"Trentino-Alte Adige (Trentino-Südtirol)",
u"IT-BZ": u"Bolzano (Bozen)",
u"IT-TN": u"Trento",
u"IT-55": u"Umbria",
u"IT-PG": u"Perugia",
u"IT-TR": u"Terni",
u"IT-23": u"Valle d'Aosta (Vallée d'Aoste)",
u"IT-AO": u"Aosta (Aoste)",
u"IT-34": u"Veneto",
u"IT-BL": u"Belluno",
u"IT-PD": u"Padova",
u"IT-RO": u"Rovigo",
u"IT-TV": u"Treviso",
u"IT-VE": u"Venezia",
u"IT-VR": u"Verona",
u"IT-VI": u"Vicenza",
u"JM-13": u"Clarendon",
u"JM-09": u"Hanover",
u"JM-01": u"Kingston",
u"JM-12": u"Manchester",
u"JM-04": u"Portland",
u"JM-02": u"Saint Andrew",
u"JM-06": u"Saint Ann",
u"JM-14": u"Saint Catherine",
u"JM-11": u"Saint Elizabeth",
u"JM-08": u"Saint James",
u"JM-05": u"Saint Mary",
u"JM-03": u"Saint Thomas",
u"JM-07": u"Trelawny",
u"JM-10": u"Westmoreland",
u"JP-23": u"Aiti [Aichi]",
u"JP-05": u"Akita",
u"JP-02": u"Aomori",
u"JP-38": u"Ehime",
u"JP-21": u"Gihu [Gifu]",
u"JP-10": u"Gunma",
u"JP-34": u"Hirosima [Hiroshima]",
u"JP-01": u"Hokkaidô [Hokkaido]",
u"JP-18": u"Hukui [Fukui]",
u"JP-40": u"Hukuoka [Fukuoka]",
u"JP-07": u"Hukusima [Fukushima]",
u"JP-28": u"Hyôgo [Hyogo]",
u"JP-08": u"Ibaraki",
u"JP-17": u"Isikawa [Ishikawa]",
u"JP-03": u"Iwate",
u"JP-37": u"Kagawa",
u"JP-46": u"Kagosima [Kagoshima]",
u"JP-14": u"Kanagawa",
u"JP-39": u"Kôti [Kochi]",
u"JP-43": u"Kumamoto",
u"JP-26": u"Kyôto [Kyoto]",
u"JP-24": u"Mie",
u"JP-04": u"Miyagi",
u"JP-45": u"Miyazaki",
u"JP-20": u"Nagano",
u"JP-42": u"Nagasaki",
u"JP-29": u"Nara",
u"JP-15": u"Niigata",
u"JP-44": u"Ôita [Oita]",
u"JP-33": u"Okayama",
u"JP-47": u"Okinawa",
u"JP-27": u"Ôsaka [Osaka]",
u"JP-41": u"Saga",
u"JP-11": u"Saitama",
u"JP-25": u"Siga [Shiga]",
u"JP-22": u"Sizuoka [Shizuoka]",
u"JP-12": u"Tiba [Chiba]",
u"JP-09": u"Totigi [Tochigi]",
u"JP-36": u"Tokusima [Tokushima]",
u"JP-13": u"Tôkyô [Tokyo]",
u"JP-31": u"Tottori",
u"JP-16": u"Toyama",
u"JP-30": u"Wakayama",
u"JP-06": u"Yamagata",
u"JP-35": u"Yamaguti [Yamaguchi]",
u"JP-19": u"Yamanasi [Yamanashi]",
u"JO-AJ": u"‘Ajlūn",
u"JO-AQ": u"Al 'Aqaba",
u"JO-BA": u"Al Balqā'",
u"JO-KA": u"Al Karak",
u"JO-MA": u"Al Mafraq",
u"JO-AM": u"‘Ammān",
u"JO-AT": u"Aţ Ţafīlah",
u"JO-AZ": u"Az Zarqā'",
u"JO-IR": u"Irbid",
u"JO-JA": u"Jarash",
u"JO-MN": u"Ma‘ān",
u"JO-MD": u"Mādaba",
u"KZ-ALA": u"Almaty",
u"KZ-BAY": u"Bayqonyr (Baykonyr)",
u"KZ-ALM": u"Almaty oblysy (Almatinskaya oblast')",
u"KZ-AKM": u"Aqmola oblysy (Akmolinskaya oblast')",
u"KZ-AKT": u"Aqtöbe oblysy (Aktyubinskaya oblast')",
u"KZ-ATY": u"Atyraü oblysy (Atyrauskaya oblast')",
u"KZ-ZAP": u"Batys Kazakstan oblysy (Zapadno-Kazakhstanskaya oblast')",
u"KZ-MAN": u"Mangghystaū oblysy (Mangystauskaya oblast')",
u"KZ-YUZ": u"Ongtüstik Kazakstan oblysy (Yuzhno-Kazakhstanskaya oblast')",
u"KZ-PAV": u"Pavlodar oblysy (Pavlodarskaya oblast')",
u"KZ-KAR": u"Qaraghandy oblysy (Karagandinskaya oblast')",
u"KZ-KUS": u"Qostanay oblysy (Kustanayskaya oblast')",
u"KZ-KZY": u"Qyzylorda oblysy (Kzylordinskaya oblast')",
u"KZ-VOS": u"Shyghys Kazakstan oblysy (Vostochno-Kazakhstanskaya oblast')",
u"KZ-SEV": u"Soltüstik Kazakstan oblysy (Severo-Kazakhstanskaya oblast')",
u"KZ-ZHA": u"Zhambyl oblysy (Zhambylskaya Oblast')",
u"KE-110": u"Nairobi Municipality",
u"KE-200": u"Central (Kati)",
u"KE-300": u"Coast (Pwani)",
u"KE-400": u"Eastern (Mashariki)",
u"KE-500": u"North-Eastern (Kaskazini Mashariki)",
u"KE-600": u"Nyanza",
u"KE-700": u"Rift Valley",
u"KE-900": u"Western (Magharibi)",
u"KI-G": u"Gilbert Islands",
u"KI-L": u"Line Islands",
u"KI-P": u"Phoenix Islands",
u"KP-KAE": u"Kaesong-si",
u"KP-NAM": u"Nampo-si",
u"KP-PYO": u"Pyongyang-si",
u"KP-CHA": u"Chagang-do",
u"KP-HAB": u"Hamgyongbuk-do",
u"KP-HAN": u"Hamgyongnam-do",
u"KP-HWB": u"Hwanghaebuk-do",
u"KP-HWN": u"Hwanghaenam-do",
u"KP-KAN": u"Kangwon-do",
u"KP-PYB": u"Pyonganbuk-do",
u"KP-PYN": u"Pyongannam-do",
u"KP-YAN": u"Yanggang-do",
u"KR-11": u"Seoul Teugbyeolsi [ Seoul-T’ŭkpyŏlshi]",
u"KR-26": u"Busan Gwang'yeogsi [Pusan-Kwangyŏkshi]",
u"KR-27": u"Daegu Gwang'yeogsi [Taegu-Kwangyŏkshi)",
u"KR-30": u"Daejeon Gwang'yeogsi [Taejŏn-Kwangyŏkshi]",
u"KR-29": u"Gwangju Gwang'yeogsi [Kwangju-Kwangyŏkshi]",
u"KR-28": u"Incheon Gwang'yeogsi [Inchŏn-Kwangyŏkshi]",
u"KR-31": u"Ulsan Gwang'yeogsi [Ulsan-Kwangyŏkshi]",
u"KR-43": u"Chungcheongbugdo [Ch'ungch'ŏngbuk-do]",
u"KR-44": u"Chungcheongnamdo [Ch'ungch'ŏngnam-do]",
u"KR-42": u"Gang'weondo [Kang-won-do]",
u"KR-41": u"Gyeonggido [Kyŏnggi-do]",
u"KR-47": u"Gyeongsangbugdo [Kyŏngsangbuk-do]",
u"KR-48": u"Gyeongsangnamdo [Kyŏngsangnam-do]",
u"KR-49": u"Jejudo [Cheju-do]",
u"KR-45": u"Jeonrabugdo [Chŏllabuk-do)",
u"KR-46": u"Jeonranamdo [Chŏllanam-do]",
u"KW-AH": u"Al Aḩmadi",
u"KW-FA": u"Al Farwānīyah",
u"KW-JA": u"Al Jahrah",
u"KW-KU": u"Al Kuwayt",
u"KW-HA": u"Ḩawallī",
u"KG-C": u"Chu (Chuyskaya oblast')",
u"KG-J": u"Jalal-Abad (Dzhalal-Abadskaya oblast')",
u"KG-N": u"Naryn (Narynskaya Oblast’)",
u"KG-O": u"Osh (Oshskaya oblast')",
u"KG-T": u"Talas (Talasskaya oblast')",
u"KG-Y": u"Ysyk-Köl (Issyk-Kul'skaya oblast')",
u"LA-VT": u"Vientiane",
u"LA-AT": u"Attapu [Attopeu]",
u"LA-BK": u"Bokèo",
u"LA-BL": u"Bolikhamxai [Borikhane]",
u"LA-CH": u"Champasak [Champassak]",
u"LA-HO": u"Houaphan",
u"LA-KH": u"Khammouan",
u"LA-LM": u"Louang Namtha",
u"LA-LP": u"Louangphabang [Louang Prabang]",
u"LA-OU": u"Oudômxai [Oudomsai]",
u"LA-PH": u"Phôngsali [Phong Saly]",
u"LA-SL": u"Salavan [Saravane]",
u"LA-SV": u"Savannakhét",
u"LA-VI": u"Vientiane",
u"LA-XA": u"Xaignabouli [Sayaboury]",
u"LA-XE": u"Xékong [Sékong]",
u"LA-XI": u"Xiangkhoang [Xieng Khouang]",
u"LV-AI": u"Aizkraukles Aprinkis",
u"LV-AL": u"Alūksnes Aprinkis",
u"LV-BL": u"Balvu Aprinkis",
u"LV-BU": u"Bauskas Aprinkis",
u"LV-CE": u"Cēsu Aprinkis",
u"LV-DA": u"Daugavpils Aprinkis",
u"LV-DO": u"Dobeles Aprinkis",
u"LV-GU": u"Gulbenes Aprinkis",
u"LV-JL": u"Jelgavas Aprinkis",
u"LV-JK": u"Jēkabpils Aprinkis",
u"LV-KR": u"Krāslavas Aprinkis",
u"LV-KU": u"Kuldīgas Aprinkis",
u"LV-LM": u"Limbažu Aprinkis",
u"LV-LE": u"Liepājas Aprinkis",
u"LV-LU": u"Ludzas Aprinkis",
u"LV-MA": u"Madonas Aprinkis",
u"LV-OG": u"Ogres Aprinkis",
u"LV-PR": u"Preilu Aprinkis",
u"LV-RE": u"Rēzeknes Aprinkis",
u"LV-RI": u"Rīgas Aprinkis",
u"LV-SA": u"Saldus Aprinkis",
u"LV-TA": u"Talsu Aprinkis",
u"LV-TU": u"Tukuma Aprinkis",
u"LV-VK": u"Valkas Aprinkis",
u"LV-VM": u"Valmieras Aprinkis",
u"LV-VE": u"Ventspils Aprinkis",
u"LV-DGV": u"Daugavpils",
u"LV-JEL": u"Jelgava",
u"LV-JUR": u"Jūrmala",
u"LV-LPX": u"Liepāja",
u"LV-REZ": u"Rēzekne",
u"LV-RIX": u"Rīga",
u"LV-VEN": u"Ventspils",
u"LB-BA": u"Beiroût (Bayrūt)",
u"LB-BI": u"El Béqaa (Al Biqā')",
u"LB-JL": u"Jabal Loubnâne (Jabal Lubnān)",
u"LB-AS": u"Loubnâne ech Chemâli (Ash Shamāl)",
u"LB-JA": u"Loubnâne ej Jnoûbi (Al Janūb)",
u"LB-NA": u"Nabatîyé (An Nabaţīyah",
u"LS-D": u"Berea",
u"LS-B": u"Butha-Buthe",
u"LS-C": u"Leribe",
u"LS-E": u"Mafeteng",
u"LS-A": u"Maseru",
u"LS-F": u"Mohale's Hoek",
u"LS-J": u"Mokhotlong",
u"LS-H": u"Qacha's Nek",
u"LS-G": u"Quthing",
u"LS-K": u"Thaba-Tseka",
u"LR-BM": u"Bomi",
u"LR-BG": u"Bong",
u"LR-GB": u"Grand Bassa",
u"LR-CM": u"Grand Cape Mount",
u"LR-GG": u"Grand Gedeh",
u"LR-GK": u"Grand Kru",
u"LR-LO": u"Lofa",
u"LR-MG": u"Margibi",
u"LR-MY": u"Maryland",
u"LR-MO": u"Montserrado",
u"LR-NI": u"Nimba",
u"LR-RI": u"Rivercess",
u"LR-SI": u"Sinoe",
u"LY-BU": u"Al Buţnān",
u"LY-JA": u"Al Jabal al Akhḑar",
u"LY-JG": u"Al Jabal al Gharbī",
u"LY-Ju": u"Al Jufrah",
u"LY-WA": u"Al Wāḩah",
u"LY-Wu": u"Al Wusţá",
u"LY-ZA": u"Az Zāwiyah",
u"LY-BA": u"Banghāzī",
u"LY-FA": u"Fazzān",
u"LY-MI": u"Mişrātah",
u"LY-NA": u"Naggaza",
u"LY-SF": u"Sawfajjin",
u"LY-TB": u"Ţarābulus",
u"LI-LI": u"Liechtenstein",
u"LT-AL": u"Alytaus Apskritis",
u"LT-KU": u"Kauno Apskritis",
u"LT-KL": u"Klaipėdos Apskritis",
u"LT-MR": u"Marijampolės Apskritis",
u"LT-PN": u"Panevėžio Apskritis",
u"LT-SA": u"Šiauliu Apskritis",
u"LT-TA": u"Tauragės Apskritis",
u"LT-TE": u"Telšiu Apskritis",
u"LT-UT": u"Utenos Apskritis",
u"LT-VL": u"Vilniaus Apskritis",
u"LU-D": u"Diekirch",
u"LU-G": u"Grevenmacher",
u"LU-L": u"Luxembourg (Luxemburg)",
u"MO-MO": u"Macau",
u"MK-MK": u"Macedonia",
u"MG-T": u"Antananarivo",
u"MG-D": u"Antsiranana",
u"MG-F": u"Fianarantsoa",
u"MG-M": u"Mahajanga",
u"MG-A": u"Toamasina",
u"MG-U": u"Toliara",
u"MW-C": u"Central",
u"MW-DE": u"Dedza",
u"MW-DO": u"Dowa",
u"MW-KS": u"Kasungu",
u"MW-LI": u"Lilongwe",
u"MW-MC": u"Mchinji",
u"MW-NK": u"Nkhotakota",
u"MW-NU": u"Ntcheu",
u"MW-NI": u"Ntchisi",
u"MW-SA": u"Salima",
u"MW-N": u"Northern",
u"MW-CT": u"Chitipa",
u"MW-KR": u"Karonga",
u"MW-MZ": u"Mzimba",
u"MW-NB": u"Nkhata Bay",
u"MW-RU": u"Rumphi",
u"MW-S": u"Southern",
u"MW-BL": u"Blantyre",
u"MW-CK": u"Chikwawa",
u"MW-CR": u"Chiradzulu",
u"MW-MH": u"Machinga",
u"MW-MG": u"Mangochi",
u"MW-MU": u"Mulanje",
u"MW-MW": u"Mwanza",
u"MW-NS": u"Nsanje",
u"MW-TH": u"Thyolo",
u"MW-ZO": u"Zomba",
u"MY-W": u"Wilayah Persekutuan Kuala Lumpur",
u"MY-L": u"Wilayah Persekutuan Labuan",
u"MY-J": u"Johor",
u"MY-K": u"Kedah",
u"MY-D": u"Kelantan",
u"MY-M": u"Melaka",
u"MY-N": u"Negeri Sembilan",
u"MY-C": u"Pahang",
u"MY-A": u"Perak",
u"MY-R": u"Perlis",
u"MY-P": u"Pulau Pinang",
u"MY-SA": u"Sabah",
u"MY-SK": u"Sarawak",
u"MY-B": u"Selangor",
u"MY-T": u"Terengganu",
u"MV-MLE": u"Male",
u"MV-02": u"Alif",
u"MV-20": u"Baa",
u"MV-17": u"Dhaalu",
u"MV-14": u"Faafu",
u"MV-27": u"Gaaf Alif",
u"MV-28": u"Gaafu Dhaalu",
u"MV-29": u"Gnaviyani",
u"MV-07": u"Haa Alif",
u"MV-23": u"Haa Dhaalu",
u"MV-26": u"Kaafu",
u"MV-05": u"Laamu",
u"MV-03": u"Lhaviyani",
u"MV-12": u"Meemu",
u"MV-25": u"Noonu",
u"MV-13": u"Raa",
u"MV-01": u"Seenu",
u"MV-24": u"Shaviyani",
u"MV-08": u"Thaa",
u"MV-04": u"Vaavu",
u"ML-BKO": u"Bamako",
u"ML-7": u"Gao",
u"ML-1": u"Kayes",
u"ML-8": u"Kidal",
u"ML-2": u"Koulikoro",
u"ML-5": u"Mopti",
u"ML-4": u"Ségou",
u"ML-3": u"Sikasso",
u"ML-6": u"Tombouctou",
u"MT-MT": u"Malta",
u"MH-L": u"Ralik chain",
u"MH-ALL": u"Ailinglapalap",
u"MH-EBO": u"Ebon",
u"MH-ENI": u"Eniwetok",
u"MH-JAL": u"Jaluit",
u"MH-KIL": u"Kili",
u"MH-KWA": u"Kwajalein",
u"MH-LAE": u"Lae",
u"MH-LIB": u"Lib",
u"MH-NMK": u"Namorik",
u"MH-NMU": u"Namu",
u"MH-RON": u"Rongelap",
u"MH-UJA": u"Ujae",
u"MH-UJL": u"Ujelang",
u"MH-WTH": u"Wotho",
u"MH-T": u"Ratak chain",
u"MH-ALK": u"Ailuk",
u"MH-ARN": u"Arno",
u"MH-AUR": u"Aur",
u"MH-LIK": u"Likiep",
u"MH-MAJ": u"Majuro",
u"MH-MAL": u"Maloelap",
u"MH-MEJ": u"Mejit",
u"MH-MIL": u"Mili",
u"MH-UTI": u"Utirik",
u"MH-WTJ": u"Wotje",
u"MQ-MQ": u"Martinique",
u"MR-NKC": u"Nouakchott",
u"MR-07": u"Adrar",
u"MR-03": u"Assaba",
u"MR-05": u"Brakna",
u"MR-08": u"Dakhlet Nouādhibou",
u"MR-04": u"Gorgol",
u"MR-10": u"Guidimaka",
u"MR-01": u"Hodh ech Chargui",
u"MR-02": u"Hodh el Gharbi",
u"MR-12": u"Inchiri",
u"MR-09": u"Tagant",
u"MR-11": u"Tiris Zemmour",
u"MR-06": u"Trarza",
u"MU-BR": u"Beau Bassin-Rose Hill",
u"MU-CU": u"Curepipe",
u"MU-PL": u"Port Louis",
u"MU-QB": u"Quatre Bornes",
u"MU-VP": u"Vacoas-Phoenix",
u"MU-BL": u"Black River",
u"MU-FL": u"Flacq",
u"MU-GP": u"Grand Port",
u"MU-MO": u"Moka",
u"MU-PA": u"Pamplemousses",
u"MU-PW": u"Plaines Wilhems",
u"MU-RR": u"Rivière du Rempart",
u"MU-SA": u"Savanne",
u"MU-AG": u"Agalega Islands",
u"MU-CC": u"Cargados Carajos Shoals [Saint Brandon Islands]",
u"MU-RO": u"Rodrigues Island",
u"YT-YT": u"Mayotte",
u"MX-DIF": u"Distrito Federal",
u"MX-AGU": u"Aguascalientes",
u"MX-BCN": u"Baja California",
u"MX-BCS": u"Baja California Sur",
u"MX-CAM": u"Campeche",
u"MX-COA": u"Coahuila",
u"MX-COL": u"Colima",
u"MX-CHP": u"Chiapas",
u"MX-CHH": u"Chihuahua",
u"MX-DUR": u"Durango",
u"MX-GRO": u"Guerrero",
u"MX-GUA": u"Guanajuato",
u"MX-HID": u"Hidalgo",
u"MX-JAL": u"Jalisco",
u"MX-MEX": u"México",
u"MX-MIC": u"Michoacán",
u"MX-MOR": u"Morelos",
u"MX-NAY": u"Nayarit",
u"MX-NLE": u"Nuevo León",
u"MX-OAX": u"Oaxaca",
u"MX-PUE": u"Puebla",
u"MX-QUE": u"Queretaro",
u"MX-ROO": u"Quintana Roo",
u"MX-SLP": u"San Luis Potosí",
u"MX-SIN": u"Sinaloa",
u"MX-SON": u"Sonora",
u"MX-TAB": u"Tabasco",
u"MX-TAM": u"Tamaulipas",
u"MX-TLA": u"Tlaxcala",
u"MX-VER": u"Veracruz",
u"MX-YUC": u"Yucatán",
u"MX-ZAC": u"Zacatecas",
u"FM-TRK": u"chuuk",
u"FM-KSA": u"Kosrae",
u"FM-PNI": u"Pohnpei",
u"FM-YAP": u"Yap",
u"MD-BAL": u"Bălţi",
u"MD-CAH": u"Cahul",
u"MD-CHI": u"Chişinău",
u"MD-DUB": u"Dubăsari",
u"MD-ORH": u"Orhei",
u"MD-RIB": u"Rîbniţa",
u"MD-SOC": u"Soroca",
u"MD-TIG": u"Tighina",
u"MD-TIR": u"Tiraspol",
u"MD-UNG": u"Ungheni",
u"MD-ANE": u"Anenii Noi",
u"MD-BAS": u"Basarabeasca",
u"MD-BRI": u"Brinceni",
u"MD-CHL": u"Cahul",
u"MD-CAM": u"Camenca",
u"MD-CAN": u"Cantemir",
u"MD-CAI": u"Căinari",
u"MD-CAL": u"Călăraşi",
u"MD-CAS": u"Căuşeni",
u"MD-CIA": u"Ciadîr-Lunga",
u"MD-CIM": u"Cimişlia",
u"MD-COM": u"Comrat",
u"MD-CRI": u"Criuleni",
u"MD-DON": u"Donduşeni",
u"MD-DRO": u"Drochia",
u"MD-DBI": u"Dubăsari",
u"MD-EDI": u"Edineţ",
u"MD-FAL": u"Făleşti",
u"MD-FLO": u"Floreşti",
u"MD-GLO": u"Glodeni",
u"MD-GRI": u"Grigoriopol",
u"MD-HIN": u"Hînceşti",
u"MD-IAL": u"Ialoveni",
u"MD-LEO": u"Leova",
u"MD-NIS": u"Nisporeni",
u"MD-OCN": u"Ocniţa",
u"MD-OHI": u"Orhei",
u"MD-REZ": u"Rezina",
u"MD-RIT": u"Rîbniţa",
u"MD-RIS": u"Rîşcani",
u"MD-SIN": u"Sîngerei",
u"MD-SLO": u"Slobozia",
u"MD-SOA": u"Soroca",
u"MD-STR": u"Străşeni",
u"MD-SOL": u"Şoldăneşti",
u"MD-STE": u"Ştefan Vodă",
u"MD-TAR": u"Taraclia",
u"MD-TEL": u"Teleneşti",
u"MD-UGI": u"Ungheni",
u"MD-VUL": u"Vulcăneşti",
u"MC-MC": u"Monaco",
u"MN-1": u"Ulaanbaatar",
u"MN-073": u"Arhangay",
u"MN-069": u"Bayanhongor",
u"MN-071": u"Bayan-Ölgiy",
u"MN-067": u"Bulgan",
u"MN-037": u"Darhan uul",
u"MN-061": u"Dornod",
u"MN-063": u"Dornogovĭ",
u"MN-059": u"Dundgovĭ",
u"MN-057": u"Dzavhan",
u"MN-065": u"Govĭ-Altay",
u"MN-064": u"Govĭ-Sümber",
u"MN-039": u"Hentiy",
u"MN-043": u"Hovd",
u"MN-041": u"Hövsgöl",
u"MN-053": u"Ömnögovĭ",
u"MN-035": u"Orhon",
u"MN-055": u"Övörhangay",
u"MN-049": u"Selenge",
u"MN-051": u"Sühbaatar",
u"MN-047": u"Töv",
u"MN-046": u"Uvs",
u"MS-MS": u"Montserrat",
u"MA-CE": u"Centre",
u"MA-AZI": u"Azilal",
u"MA-BEM": u"Beni Mellal",
u"MA-BES": u"Ben Slimane",
u"MA-BOM": u"Boulemane",
u"MA-CAS": u"Casablanca [Dar el Beïda]",
u"MA-JDI": u"El Jadida",
u"MA-KHO": u"Khouribga",
u"MA-SET": u"Settat",
u"MA-CN": u"Centre-Nord",
u"MA-HOC": u"Al Hoceïma",
u"MA-FES": u"Fès",
u"MA-SEF": u"Sefrou",
u"MA-TAO": u"Taounate",
u"MA-TAZ": u"Taza",
u"MA-CS": u"Centre-Sud",
u"MA-HAJ": u"El Hajeb",
u"MA-ERR": u"Errachidia",
u"MA-IFR": u"Ifrane",
u"MA-KHN": u"Khenifra",
u"MA-MEK": u"Meknès",
u"MA-ES": u"Est",
u"MA-BER": u"Berkane",
u"MA-FIG": u"Figuig",
u"MA-IRA": u"Jrada",
u"MA-NAD": u"Nador",
u"MA-OUJ": u"Oujda",
u"MA-NO": u"Nord-Ouest",
u"MA-CHE": u"Chefchaouene",
u"MA-KEN": u"Kénitra",
u"MA-KHE": u"Khemisset",
u"MA-LAR": u"Larache",
u"MA-RBA": u"Rabat-Salé",
u"MA-SIK": u"Sidi Kacem",
u"MA-TNG": u"Tanger",
u"MA-TET": u"Tétouan",
u"MA-SU": u"Sud",
u"MA-AGD": u"Agadir",
u"MA-BAH": u"Aït Baha",
u"MA-MEL": u"Aït Melloul",
u"MA-ASZ": u"Assa-Zag",
u"MA-BOD": u"Boujdour (EH)",
u"MA-ESM": u"Es Semara (EH)",
u"MA-GUE": u"Guelmim",
u"MA-LAA": u"Laayoune (EH)",
u"MA-OUA": u"Ouarzazate",
u"MA-OUD": u"Oued ed Dahab (EH)",
u"MA-TNT": u"Tan-Tan",
u"MA-TAR": u"Taroudannt",
u"MA-TAT": u"Tata",
u"MA-TIZ": u"Tiznit",
u"MA-TS": u"Tensift",
u"MA-HAO": u"Al Haouz",
u"MA-CHI": u"Chichaoua",
u"MA-ESI": u"Essaouira",
u"MA-KES": u"Kelaat Sraghna",
u"MA-MAR": u"Marrakech",
u"MA-SAF": u"Safi",
u"MZ-MPM": u"Maputo",
u"MZ-P": u"Cabo Delgado",
u"MZ-G": u"Gaza",
u"MZ-I": u"Inhambane",
u"MZ-B": u"Manica",
u"MZ-L": u"Maputo",
u"MZ-N": u"Nampula",
u"MZ-A": u"Niassa",
u"MZ-S": u"Sofala",
u"MZ-T": u"Tete",
u"MZ-Q": u"Zambézia",
u"MM-07": u"Ayeyarwady",
u"MM-02": u"Bago",
u"MM-03": u"Magway",
u"MM-04": u"Mandalay",
u"MM-01": u"Sagaing",
u"MM-05": u"Tanintharyi",
u"MM-06": u"Yangon",
u"MM-14": u"Chin",
u"MM-11": u"Kachin",
u"MM-12": u"Kayah",
u"MM-13": u"Kayin",
u"MM-15": u"Mon",
u"MM-16": u"Rakhine",
u"MM-17": u"Shan",
u"NA-CA": u"Caprivi",
u"NA-ER": u"Erongo",
u"NA-HA": u"Hardap",
u"NA-KA": u"Karas",
u"NA-KH": u"Khomas",
u"NA-KU": u"Kunene",
u"NA-OW": u"Ohangwena",
u"NA-OK": u"Okavango",
u"NA-OH": u"Omaheke",
u"NA-OS": u"Omusati",
u"NA-ON": u"Oshana",
u"NA-OT": u"Oshikoto",
u"NA-OD": u"Otjozondjupa",
u"NR-NR": u"Nauru",
u"NP-1": u"Madhyamanchal",
u"NP-BA": u"Bagmati",
u"NP-JA": u"Janakpur",
u"NP-NA": u"Narayani",
u"NP-2": u"Madhya Pashchimanchal",
u"NP-BH": u"Bheri",
u"NP-KA": u"Karnali",
u"NP-RA": u"Rapti",
u"NP-3": u"Pashchimanchal",
u"NP-DH": u"Dhawalagiri",
u"NP-GA": u"Gandaki",
u"NP-LU": u"Lumbini",
u"NP-4": u"Purwanchal",
u"NP-KO": u"Kosi [Koshi]",
u"NP-ME": u"Mechi",
u"NP-SA": u"Sagarmatha",
u"NP-5": u"Sudur Pashchimanchal",
u"NP-MA": u"Mahakali",
u"NP-SE": u"Seti",
u"NL-DR": u"Drenthe",
u"NL-FL": u"Flevoland",
u"NL-FR": u"Friesland",
u"NL-GE": u"Gelderland",
u"NL-GR": u"Groningen",
u"NL-LI": u"Limburg",
u"NL-NB": u"Noord-Brabant",
u"NL-NH": u"Noord-Holland",
u"NL-OV": u"Overijssel",
u"NL-UT": u"Utrecht",
u"NL-ZE": u"Zeeland",
u"NL-ZH": u"Zuid-Holland",
u"AN-AN": u"Netherlands Antilles",
u"NC-NC": u"New Caledonia",
u"NZ-N": u"North Island",
u"NZ-AUK": u"Auckland",
u"NZ-BOP": u"Bay of Plenty",
u"NZ-GIS": u"Gisborne",
u"NZ-HKB": u"Hawkes's Bay",
u"NZ-MWT": u"Manawatu-Wanganui",
u"NZ-NTL": u"Northland",
u"NZ-TKI": u"Taranaki",
u"NZ-WKO": u"Waikato",
u"NZ-WGN": u"Wellington",
u"NZ-S": u"South Island",
u"NZ-CAN": u"Canterbury",
u"NZ-MBH": u"Marlborough",
u"NZ-NSN": u"Nelson",
u"NZ-OTA": u"Otago",
u"NZ-STL": u"Southland",
u"NZ-TAS": u"Tasman",
u"NZ-WTC": u"West Coast",
u"NI-BO": u"Boaco",
u"NI-CA": u"Carazo",
u"NI-CI": u"Chinandega",
u"NI-CO": u"Chontales",
u"NI-ES": u"Estelí",
u"NI-GR": u"Granada",
u"NI-JI": u"Jinotega",
u"NI-LE": u"León",
u"NI-MD": u"Madriz",
u"NI-MN": u"Manaqua",
u"NI-MS": u"Masaya",
u"NI-MT": u"Matagalpa",
u"NI-NS": u"Nueva Segovia",
u"NI-SJ": u"Río San Juan",
u"NI-RI": u"Rivas",
u"NI-ZE": u"Zelaya",
u"NE-8": u"Niamey",
u"NE-1": u"Agadez",
u"NE-2": u"Diffa",
u"NE-3": u"Dosso",
u"NE-4": u"Maradi",
u"NE-5": u"Tahoua",
u"NE-6": u"Tillaberi",
u"NE-7": u"Zinder",
u"NG-FC": u"Abuja Capital Territory",
u"NG-AB": u"Abia",
u"NG-AD": u"Adamawa",
u"NG-AK": u"Akwa Ibom",
u"NG-AN": u"Anambra",
u"NG-BA": u"Bauchi",
u"NG-BE": u"Benue",
u"NG-BO": u"Borno",
u"NG-CR": u"Cross River",
u"NG-DE": u"Delta",
u"NG-ED": u"Edo",
u"NG-EN": u"Enugu",
u"NG-IM": u"Imo",
u"NG-JI": u"Jigawa",
u"NG-KD": u"Kaduna",
u"NG-KN": u"Kano",
u"NG-KT": u"Katsina",
u"NG-KE": u"Kebbi",
u"NG-KO": u"Kogi",
u"NG-KW": u"Kwara",
u"NG-LA": u"Lagos",
u"NG-NI": u"Niger",
u"NG-OG": u"Ogun",
u"NG-ON": u"Ondo",
u"NG-OS": u"Osun",
u"NG-OY": u"Oyo",
u"NG-PL": u"Plateau",
u"NG-RI": u"Rivers",
u"NG-SO": u"Sokoto",
u"NG-TA": u"Taraba",
u"NG-YO": u"Yobe",
u"NU-NU": u"Niue",
u"NF-NF": u"Norfolk Island",
u"MP-MP": u"Northern Mariana Islands",
u"NO-02": u"Akershus",
u"NO-09": u"Aust-Agder",
u"NO-06": u"Buskerud",
u"NO-20": u"Finnmark",
u"NO-04": u"Hedmark",
u"NO-12": u"Hordaland",
u"NO-15": u"Møre og Romsdal",
u"NO-18": u"Nordland",
u"NO-17": u"Nord-Trøndelag",
u"NO-05": u"Oppland",
u"NO-03": u"Oslo",
u"NO-11": u"Rogaland",
u"NO-14": u"Sogn og Fjordane",
u"NO-16": u"Sør-Trøndelag",
u"NO-08": u"Telemark",
u"NO-19": u"Troms",
u"NO-10": u"Vest-Agder",
u"NO-07": u"Vestfold",
u"NO-01": u"Østfold",
u"NO-22": u"Jan Mayen (Arctic Region)",
u"NO-21": u"Svalbard (Arctic Region)",
u"OM-DA": u"Ad Dākhilīyah",
u"OM-BA": u"Al Bāţinah",
u"OM-JA": u"Al Janūbīyah [Zufār]",
u"OM-WU": u"Al Wusţā",
u"OM-SH": u"Ash Sharqīyah",
u"OM-ZA": u"Az Zāhirah",
u"OM-MA": u"Masqaţ",
u"OM-MU": u"Musandam",
u"PK-IS": u"Islamabad",
u"PK-BA": u"Baluchistan (Balochistān)",
u"PK-NW": u"North-West Frontier",
u"PK-PB": u"Punjab",
u"PK-SD": u"Sind (Sindh)",
u"PK-TA": u"Federally Administered Tribal Areas",
u"PK-JK": u"Azad Kashmir",
u"PK-NA": u"Northern Areas",
u"PW-PW": u"Palau",
u"PA-1": u"Botas del Toro",
u"PA-2": u"Coclé",
u"PA-3": u"Colón",
u"PA-4": u"Chiriquī",
u"PA-5": u"Darién",
u"PA-6": u"Herrera",
u"PA-7": u"Los Santos",
u"PA-8": u"Panamá",
u"PA-9": u"Veraguas",
u"PA-0": u"Comarca de San Blas",
u"PG-NCD": u"National Capital District (Port Moresby)",
u"PG-CPM": u"Central",
u"PG-CPK": u"Chimbu",
u"PG-EHG": u"Eastern Highlands",
u"PG-EBR": u"East New Britain",
u"PG-ESW": u"East Sepik",
u"PG-EPW": u"Enga",
u"PG-GPK": u"Gulf",
u"PG-MPM": u"Madang",
u"PG-MRL": u"Manus",
u"PG-MBA": u"Milne Bay",
u"PG-MPL": u"Morobe",
u"PG-NIK": u"New Ireland",
u"PG-NPP": u"Northern",
u"PG-NSA": u"North Solomons",
u"PG-SAN": u"Sandaun [West Sepik]",
u"PG-SHM": u"Southern Highlands",
u"PG-WPD": u"Western",
u"PG-WHM": u"Western Highlands",
u"PG-WBK": u"West New Britain",
u"PY-ASU": u"Asunción",
u"PY-16": u"Alto Paraguay",
u"PY-10": u"Alto Parang",
u"PY-13": u"Amambay",
u"PY-19": u"Boquerón",
u"PY-5": u"Caaguazú",
u"PY-6": u"Caazapá",
u"PY-14": u"Canindeyú",
u"PY-11": u"Central",
u"PY-1": u"Concepción",
u"PY-3": u"Cordillera",
u"PY-4": u"Guairá",
u"PY-7": u"Itapúa",
u"PY-8": u"Misiones",
u"PY-12": u"Neembucú",
u"PY-9": u"Paraguarī",
u"PY-15": u"Presidente Hayes",
u"PY-2": u"San Pedro",
u"PE-CAL": u"El Callao",
u"PE-AMA": u"Amazonas",
u"PE-ANC": u"Ancash",
u"PE-APU": u"Apurímac",
u"PE-ARE": u"Arequipa",
u"PE-AYA": u"Ayacucho",
u"PE-CAJ": u"Cajamarca",
u"PE-CUS": u"Cuzco [Cusco]",
u"PE-HUV": u"Huancavelica",
u"PE-HUC": u"Huánuco",
u"PE-ICA": u"Ica",
u"PE-JUN": u"Junín",
u"PE-LAL": u"La Libertad",
u"PE-LAM": u"Lambayeque",
u"PE-LIM": u"Lima",
u"PE-LOR": u"Loreto",
u"PE-MDD": u"Madre de Dios",
u"PE-MOQ": u"Moquegua",
u"PE-PAS": u"Pasco",
u"PE-PIU": u"Piura",
u"PE-PUN": u"Puno",
u"PE-SAM": u"San Martín",
u"PE-TAC": u"Tacna",
u"PE-TUM": u"Tumbes",
u"PE-UCA": u"Ucayali",
u"PH-PH": u"Philippines",
u"PN-PN": u"Pitcairn",
u"PL-BP": u"Biała Podlaska",
u"PL-BK": u"Białystok",
u"PL-BB": u"Bielsko",
u"PL-BY": u"Bydgoszcz",
u"PL-CH": u"Chełm",
u"PL-CI": u"Ciechanów",
u"PL-CZ": u"Czestochowa",
u"PL-EL": u"Elblag",
u"PL-GD": u"Gdańsk",
u"PL-GO": u"Gorzów",
u"PL-JG": u"Jelenia Gera",
u"PL-KL": u"Kalisz",
u"PL-KA": u"Katowice",
u"PL-KI": u"Kielce",
u"PL-KN": u"Konin",
u"PL-KO": u"Koszalin",
u"PL-KR": u"Kraków",
u"PL-KS": u"Krosno",
u"PL-LG": u"Legnica",
u"PL-LE": u"Leszno",
u"PL-LU": u"Lublin",
u"PL-LO": u"Łomia",
u"PL-LD": u"Łódź",
u"PL-NS": u"Nowy Sacz",
u"PL-OL": u"Olsztyn",
u"PL-OP": u"Opole",
u"PL-OS": u"Ostrołeka",
u"PL-PI": u"Piła",
u"PL-PT": u"Piotrków",
u"PL-PL": u"Płock",
u"PL-PO": u"Poznań",
u"PL-PR": u"Przemyśl",
u"PL-RA": u"Radom",
u"PL-RZ": u"Rzeszów",
u"PL-SE": u"Siedlce",
u"PL-SI": u"Sieradz",
u"PL-SK": u"Skierniewice",
u"PL-SL": u"Słupsk",
u"PL-SU": u"Suwałki",
u"PL-SZ": u"Szczecin",
u"PL-TG": u"Tarnobrzeg",
u"PL-TA": u"Tarnów",
u"PL-TO": u"Toruń",
u"PL-WB": u"Wałbrzych",
u"PL-WA": u"Warszawa",
u"PL-WL": u"Włocławek",
u"PL-WR": u"Wrocław",
u"PL-ZA": u"Zamość",
u"PL-ZG": u"Zielona Góra",
u"PT-01": u"Aveiro",
u"PT-02": u"Beja",
u"PT-03": u"Braga",
u"PT-04": u"Bragança",
u"PT-05": u"Castelo Branco",
u"PT-06": u"Coimbra",
u"PT-07": u"Évora",
u"PT-08": u"Faro",
u"PT-09": u"Guarda",
u"PT-10": u"Leiria",
u"PT-11": u"Lisboa",
u"PT-12": u"Portalegre",
u"PT-13": u"Porto",
u"PT-14": u"Santarém",
u"PT-15": u"Setúbal",
u"PT-16": u"Viana do Castelo",
u"PT-17": u"Vila Real",
u"PT-18": u"Viseu",
u"PT-20": u"Regiāo Autónoma dos Açores",
u"PT-30": u"Regiāo Autónoma da Madeira",
u"PR-PR": u"Puerto Rico",
u"QA-DA": u"Ad Dawḩah",
u"QA-GH": u"Al Ghuwayrīyah",
u"QA-JU": u"Al Jumaylīyah",
u"QA-KH": u"Al Khawr",
u"QA-WA": u"Al Wakrah",
u"QA-RA": u"Ar Rayyān",
u"QA-JB": u"Jarīyān al Bāţnah",
u"QA-MS": u"Madīnat ash Shamāl",
u"QA-US": u"Umm Şalāl",
u"RE-RE": u"Reunion",
u"RO-B": u"Bucureşti",
u"RO-AB": u"Alba",
u"RO-AR": u"Arad",
u"RO-AG": u"Argeş",
u"RO-BC": u"Bacău",
u"RO-BH": u"Bihor",
u"RO-BN": u"Bistriţa-Năsăud",
u"RO-BT": u"Botoşani",
u"RO-BV": u"Braşov",
u"RO-BR": u"Brăila",
u"RO-BZ": u"Buzău",
u"RO-CS": u"Caraş-Severin",
u"RO-CL": u"Călăraşi",
u"RO-CJ": u"Cluj",
u"RO-CT": u"Constanţa",
u"RO-CV": u"Covasna",
u"RO-DB": u"Dâmboviţa",
u"RO-DJ": u"Dolj",
u"RO-GL": u"Galaţi",
u"RO-GR": u"Giurgiu",
u"RO-GJ": u"Gorj",
u"RO-HR": u"Harghita",
u"RO-HD": u"Hunedoara",
u"RO-IL": u"Ialomiţa",
u"RO-IS": u"Iaşi",
u"RO-MM": u"Maramureş",
u"RO-MH": u"Mehedinţi",
u"RO-MS": u"Mureş",
u"RO-NT": u"Neamţ",
u"RO-OT": u"Olt",
u"RO-PH": u"Prahova",
u"RO-SM": u"Satu Mare",
u"RO-SJ": u"Sălaj",
u"RO-SB": u"Sibiu",
u"RO-SV": u"Suceava",
u"RO-TR": u"Teleorman",
u"RO-TM": u"Timiş",
u"RO-TL": u"Tulcea",
u"RO-VS": u"Vaslui",
u"RO-VL": u"Vâlcea",
u"RO-VN": u"Vrancea",
u"RU-AD": u"Adygeya, Respublika",
u"RU-AL": u"Altay, Respublika",
u"RU-BA": u"Bashkortostan, Respublika",
u"RU-BU": u"Buryatiya, Respublika",
u"RU-CE": u"Chechenskaya Respublika",
u"RU-CU": u"Chuvashskaya Respublika",
u"RU-DA": u"Dagestan, Respublika",
u"RU-IN": u"Ingushskaya Respublika",
u"RU-KB": u"Kabardino-Balkarskaya Respublika",
u"RU-KL": u"Kalmykiya, Respublika",
u"RU-KC": u"Karachayevo-Cherkesskaya Respublika",
u"RU-KR": u"Kareliya, Respublika",
u"RU-KK": u"Khakasiya, Respublika",
u"RU-KO": u"Komi, Respublika",
u"RU-ME": u"Mariy El, Respublika",
u"RU-MO": u"Mordoviya, Respublika",
u"RU-SA": u"Sakha, Respublika [Yakutiya]",
u"RU-SE": u"Severnaya Osetiya, Respublika [Alaniya]",
u"RU-TA": u"Tatarstan, Respublika",
u"RU-TY": u"Tyva, Respublika [Tuva]",
u"RU-UD": u"Udmurtskaya Respublika",
u"RU-ALT": u"Altayskiy kray",
u"RU-KHA": u"Khabarovskiy kray",
u"RU-KDA": u"Krasnodarskiy kray",
u"RU-KYA": u"Krasnoyarskiy kray",
u"RU-PRI": u"Primorskiy kray",
u"RU-STA": u"Stavropol 'skiy kray",
u"RU-AMU": u"Amurskaya Oblast'",
u"RU-ARK": u"Arkhangel'skaya Oblast'",
u"RU-AST": u"Astrakhanskaya Oblast'",
u"RU-BEL": u"Belgorodskaya Oblast'",
u"RU-BRY": u"Bryanskaya Oblast'",
u"RU-CHE": u"Chelyabinskaya Oblast'",
u"RU-CHI": u"Chitinskaya Oblast'",
u"RU-IRK": u"Irkutskaya Oblast'",
u"RU-IVA": u"Ivanovskaya Oblast'",
u"RU-KGD": u"Kaliningradskaya Oblast'",
u"RU-KLU": u"Kaluzhskaya Oblast'",
u"RU-KAM": u"Kamchatskaya Oblast'",
u"RU-KEM": u"Kemerovskaya Oblast'",
u"RU-KIR": u"Kirovskaya Oblast'",
u"RU-KOS": u"Kostromskaya Oblast'",
u"RU-KGN": u"Kurganskaya Oblast'",
u"RU-KRS": u"Kurskaya Oblast'",
u"RU-LEN": u"Leningradskaya Oblast'",
u"RU-LIP": u"Lipetskaya Oblast'",
u"RU-MAG": u"Magadanskaya Oblast'",
u"RU-MOS": u"Moskovskaya Oblast'",
u"RU-MUR": u"Murmanskaya Oblast'",
u"RU-NIZ": u"Nizhegorodskaya Oblast'",
u"RU-NGR": u"Novgorodskaya Oblast'",
u"RU-NVS": u"Novosibirskaya Oblast'",
u"RU-OMS": u"Omskaya Oblast'",
u"RU-ORE": u"Orenburgskaya Oblast'",
u"RU-ORL": u"Orlovskaya Oblast'",
u"RU-PNZ": u"Penzenskaya Oblast'",
u"RU-PER": u"Permskaya Oblast'",
u"RU-PSK": u"Pskovskaya Oblast'",
u"RU-ROS": u"Rostovskaya Oblast'",
u"RU-RYA": u"Ryazanskaya Oblast'",
u"RU-SAK": u"Sakhalinskaya Oblast'",
u"RU-SAM": u"Samarskaya Oblast’",
u"RU-SAR": u"Saratovskaya Oblast'",
u"RU-SMO": u"Smolenskaya Oblast'",
u"RU-SVE": u"Sverdlovskaya Oblast'",
u"RU-TAM": u"Tambovskaya Oblast'",
u"RU-TOM": u"Tomskaya Oblast’",
u"RU-TUL": u"Tul'skaya Oblast'",
u"RU-TVE": u"Tverskaya Oblast'",
u"RU-TYU": u"Tyumenskaya Oblast'",
u"RU-ULY": u"Ul'yanovskaya Oblast'",
u"RU-VLA": u"Vladimirskaya Oblast'",
u"RU-VGG": u"Volgogradskaya Oblast'",
u"RU-VLG": u"Vologodskaya Oblast'",
u"RU-VOR": u"Voronezhskaya Oblast'",
u"RU-YAR": u"Yaroslavskaya Oblast'",
u"RU-MOW": u"Moskva",
u"RU-SPE": u"Sankt-Peterburg",
u"RU-YEV": u"Yevreyskaya avtonomnaya oblast'",
u"RU-AGB": u"Aginskiy Buryatskiy avtonomnyy okrug",
u"RU-CHU": u"Chukotskiy avtonomnyy okrug",
u"RU-EVE": u"Evenkiyskiy avtonomnyy okrug",
u"RU-KHM": u"Khanty-Mansiyskiy avtonomnyy okrug",
u"RU-KOP": u"Komi-Permyatskiy avtonomnyy okrug",
u"RU-KOR": u"Koryakskiy avtonomnyy okrug",
u"RU-NEN": u"Nenetskiy avtonomnyy okrug",
u"RU-TAY": u"Taymyrskiy (Dolgano-Nenetskiy) avtonomnyy okrug",
u"RU-UOB": u"Ust’-Ordynskiy Buryatskiy avtonomnyy okrug",
u"RU-YAN": u"Yamalo-Nenetskiy avtonomnyy okrug",
u"RW-C": u"Butare",
u"RW-I": u"Byumba",
u"RW-E": u"Cyangugu",
u"RW-D": u"Gikongoro",
u"RW-G": u"Gisenyi",
u"RW-B": u"Gitarama",
u"RW-J": u"Kibungo",
u"RW-F": u"Kibuye",
u"RW-K": u"Kigali-Rural (Kigali y’ Icyaro)",
u"RW-L": u"Kigali-Ville (Kilgali Ngari)",
u"RW-M": u"Mutara",
u"RW-H": u"Ruhengeri",
u"SH-SH": u"Saint Helena",
u"SH-AC": u"Ascension",
u"SH-TA": u"Tristan da Cunha",
u"KN-KN": u"Saint Kitts & Nevis",
u"LC-LC": u"Saint Lucia",
u"PM-PM": u"St. Pierre & Miquelon",
u"VC-VC": u"St. Vincent & the Grenadines",
u"WS-AA": u"A'ana",
u"WS-AL": u"Aiga-i-le-Tai",
u"WS-AT": u"Atua",
u"WS-FA": u"Fa'asaleleaga",
u"WS-GE": u"Gaga'emauga",
u"WS-GI": u"Gagaifomauga",
u"WS-PA": u"Palauli",
u"WS-SA": u"Satupa'itea",
u"WS-TU": u"Tuamasaga",
u"WS-VF": u"Va'a-o-Fonoti",
u"WS-VS": u"Vaisigano",
u"SM-SM": u"San Marino",
u"ST-P": u"Príncipe",
u"ST-S": u"Sāo Tomé",
u"SA-11": u"Al Bāḩah",
u"SA-08": u"Al Ḩudūd ash Shamālīyah",
u"SA-12": u"Al Jawf",
u"SA-03": u"Al Madīnah",
u"SA-05": u"Al Qaşim",
u"SA-O1": u"Ar Riyāḑ",
u"SA-04": u"Ash Sharqīyah",
u"SA-14": u"‘Asīr",
u"SA-06": u"Ḩā'il",
u"SA-09": u"Jīzān",
u"SA-02": u"Makkah",
u"SA-10": u"Najrān",
u"SA-07": u"Tabūk",
u"SN-DK": u"Dakar",
u"SN-DB": u"Diourbel",
u"SN-FK": u"Fatick",
u"SN-KL": u"Kaolack",
u"SN-KD": u"Kolda",
u"SN-LG": u"Louga",
u"SN-SL": u"Saint-Louis",
u"SN-TC": u"Tambacounda",
u"SN-TH": u"Thiès",
u"SN-ZG": u"Ziguinchor",
u"SC-SC": u"Seychelles",
u"SL-W": u"Western Area (Freetown)",
u"SL-E": u"Eastern",
u"SL-N": u"Northern",
u"SL-S": u"Southern",
u"SG-SG": u"Singapore",
u"SK-BC": u"Banskobystrický kraj",
u"SK-BL": u"Bratislavský kraj",
u"SK-KI": u"Košický kraj",
u"SK-NI": u"Nitriansky kraj",
u"SK-PV": u"Prešovský kraj",
u"SK-TC": u"Trenčiansky kraj",
u"SK-TA": u"Trnavský kraj",
u"SK-ZI": u"Žilinský kraj",
u"SI-07": u"Dolenjska",
u"SI-09": u"Gorenjska",
u"SI-11": u"Goriška",
u"SI-03": u"Koroška",
u"SI-10": u"Notranjsko-kraška",
u"SI-12": u"Obalno-kraška",
u"SI-08": u"Osrednjeslovenska",
u"SI-02": u"Podravska",
u"SI-01": u"Pomurska",
u"SI-04": u"Savinjska",
u"SI-06": u"Spodnjeposavska",
u"SI-05": u"Zasavska",
u"SB-CT": u"Capital Territory (Honiara)",
u"SB-CE": u"Central",
u"SB-GU": u"Guadalcanal",
u"SB-IS": u"Isabel",
u"SB-MK": u"Makira",
u"SB-ML": u"Malaita",
u"SB-TE": u"Temotu",
u"SB-WE": u"Western",
u"SO-AW": u"Awdal",
u"SO-BK": u"Bakool",
u"SO-BN": u"Banaadir",
u"SO-BR": u"Bari",
u"SO-BY": u"BaY",
u"SO-GA": u"Galguduud",
u"SO-GE": u"Gedo",
u"SO-HI": u"Hiiraan",
u"SO-JD": u"Jubbada Dhexe",
u"SO-JH": u"Jubbada Hoose",
u"SO-MU": u"Mudug",
u"SO-NU": u"Nugaal",
u"SO-SA": u"Sanaag",
u"SO-SD": u"Shabeellaha Dhexe",
u"SO-SH": u"Shabeellaha Hoose",
u"SO-SO": u"Sool",
u"SO-TO": u"Togdheer",
u"SO-WO": u"Woqooyi Galbeed",
u"ZA-EC": u"Eastern Cape (Oos-Kaap)",
u"ZA-FS": u"Free State (Vrystaat)",
u"ZA-GT": u"Gauteng",
u"ZA-NL": u"Kwazulu-Natal",
u"ZA-MP": u"Mpumalanga",
u"ZA-NC": u"Northern Cape (Noord-Kaap)",
u"ZA-NP": u"Northern Province (Noordelike Provinsie)",
u"ZA-NW": u"North-West (Noord-Wes)",
u"ZA-WC": u"Western Cape (Wes-Kaap)",
u"GS-GS": u"S.Georgia & S.Sandwich Islands",
u"ES-AN": u"Andalucía",
u"ES-AL": u"Almería",
u"ES-CA": u"Cádiz",
u"ES-CO": u"Córdoba",
u"ES-GR": u"Granada",
u"ES-H": u"Huelva",
u"ES-J": u"Jaén",
u"ES-MA": u"Málaga",
u"ES-SE": u"Sevilla",
u"ES-AR": u"Aragón",
u"ES-HU": u"Huesca",
u"ES-TE": u"Teruel",
u"ES-Z": u"Zaragoza",
u"ES-O": u"Asturias, Principado de",
u"ES-O": u"Asturias",
u"ES-CN": u"Canarias",
u"ES-GC": u"Las Palmas",
u"ES-TF": u"Santa Cruz De Tenerife",
u"ES-S": u"Cantabria",
u"ES-S": u"Cantabria",
u"ES-CM": u"Castilla-La Mancha",
u"ES-AB": u"Albacete",
u"ES-CR": u"Ciudad Real",
u"ES-CU": u"Cuenca",
u"ES-GU": u"Guadalajara",
u"ES-TO": u"Toledo",
u"ES-CL": u"Castilla y León",
u"ES-AV": u"Ávila",
u"ES-BU": u"Burgos",
u"ES-LE": u"León",
u"ES-P": u"Palencia",
u"ES-SA": u"Salamanca",
u"ES-SG": u"Segovia",
u"ES-SO": u"Soria",
u"ES-VA": u"Valladolid",
u"ES-ZA": u"Zamora",
u"ES-CT": u"Cataluña",
u"ES-B": u"Barcelona",
u"ES-GE": u"Gerona",
u"ES-L": u"Lérida",
u"ES-T": u"Tarragona",
u"ES-EX": u"Extremadura",
u"ES-BA": u"Badajoz",
u"ES-CC": u"Cáceres",
u"ES-GA": u"Galicia",
u"ES-C": u"La Coruña",
u"ES-LU": u"Lugo",
u"ES-OR": u"Orense",
u"ES-PO": u"Pontevedra",
u"ES-PM": u"Islas Baleares",
u"ES-PM": u"Baleares",
u"ES-LO": u"La Rioja",
u"ES-LO": u"La Rioja",
u"ES-M": u"Madrid, Comunidad de",
u"ES-M": u"Madrid",
u"ES-MU": u"Murcia, Región de",
u"ES-MU": u"Murcia",
u"ES-NA": u"Navarra, Comunidad Foral de",
u"ES-NA": u"Navarra",
u"ES-PV": u"País Vasco",
u"ES-VI": u"Álava",
u"ES-SS": u"Guipúzcoa",
u"ES-BI": u"Vizcaya",
u"ES-VC": u"Valenciana, Comunidad",
u"ES-A": u"Alicante",
u"ES-CS": u"Castellón",
u"ES-V": u"Valencia",
u"LK-1": u"Basnahira Palata (Western Province)",
u"LK-11": u"Colombo",
u"LK-12": u"Gampaha",
u"LK-13": u"Kalutara",
u"LK-3": u"Dakunu Palata (Southern Province)",
u"LK-31": u"Galle",
u"LK-33": u"Hambantota",
u"LK-32": u"Matara",
u"LK-2": u"Madhyama Palata (Central Province)",
u"LK-21": u"Kandy",
u"LK-22": u"Matale",
u"LK-23": u"Nuwara Eliya",
u"LK-5": u"Negenahira Palata (Eastern Province)",
u"LK-52": u"Arnpara",
u"LK-51": u"Batticaloa",
u"LK-53": u"Trincomalee",
u"LK-9": u"Sabaragamuwa Palata",
u"LK-92": u"Kegalla",
u"LK-91": u"Ratnapura",
u"LK-7": u"Uturumeda Palata (North Central Province)",
u"LK-71": u"Anuradhapura",
u"LK-72": u"Polonnaruwa",
u"LK-4": u"Uturu Palata (Northern Province)",
u"LK-41": u"Jaffna",
u"LK-42": u"Kilinochchi",
u"LK-43": u"Mannar",
u"LK-45": u"Mullaittivu",
u"LK-44": u"Vavuniya",
u"LK-8": u"Uva Palata",
u"LK-81": u"Badulla",
u"LK-82": u"Monaragala",
u"LK-6": u"Wayamba Palata (North Western Province)",
u"LK-61": u"Kurunegala",
u"LK-62": u"Puttalam",
u"SD-23": u"A‘ālī an Nīl",
u"SD-26": u"Al Baḩr al Aḩmar",
u"SD-18": u"Al Buḩayrāt",
u"SD-07": u"Al Jazīrah",
u"SD-03": u"Al Kharţūm",
u"SD-06": u"Al Qaḑārif",
u"SD-22": u"Al Waḩdah",
u"SD-04": u"An Nīl",
u"SD-08": u"An Nīl al Abyaḑ",
u"SD-24": u"An Nīl al Azraq",
u"SD-01": u"Ash Shamālīyah",
u"SD-17": u"Baḩr al Jabal",
u"SD-16": u"Gharb al Istiwā'īyah",
u"SD-14": u"Gharb Baḩr al Ghazāl",
u"SD-12": u"Gharb Dārfūr",
u"SD-10": u"Gharb Kurdufān",
u"SD-11": u"Janūb Dārfūr",
u"SD-13": u"Janūb Kurdufān",
u"SD-20": u"Jūnqalī",
u"SD-05": u"Kassalā",
u"SD-15": u"Shamāl Baḩr al Ghazāl",
u"SD-02": u"Shamāl Dārfūr",
u"SD-09": u"Shamāl Kurdufān",
u"SD-19": u"Sharq al Istiwā'iyah",
u"SD-25": u"Sinnār",
u"SD-21": u"Wārāb",
u"SR-BR": u"Brokopondo",
u"SR-CM": u"Commewijne",
u"SR-CR": u"Coronie",
u"SR-MA": u"Marowijne",
u"SR-NI": u"Nickerie",
u"SR-PR": u"Para",
u"SR-PM": u"Paramaribo",
u"SR-SA": u"Saramacca",
u"SR-SI": u"Sipaliwini",
u"SR-WA": u"Wanica",
u"SJ-SJ": u"Svalbard & Jan Mayen Islands",
u"SZ-HH": u"Hhohho",
u"SZ-LU": u"Lubombo",
u"SZ-MA": u"Manzini",
u"SZ-SH": u"Shiselweni",
u"SE-K": u"Blekinge län",
u"SE-W": u"Dalarnas län",
u"SE-I": u"Gotlands län",
u"SE-X": u"Gävleborgs län",
u"SE-N": u"Hallands län",
u"SE-Z": u"Jämtlands län",
u"SE-F": u"Jönköpings län",
u"SE-H": u"Kalmar län",
u"SE-G": u"Kronobergs län",
u"SE-BD": u"Norrbottens län",
u"SE-M": u"Skåne län",
u"SE-AB": u"Stockholms län",
u"SE-D": u"Södermanlands län",
u"SE-C": u"Uppsala län",
u"SE-S": u"Värmlands län",
u"SE-AC": u"Västerbottens län",
u"SE-Y": u"Västernorrlands län",
u"SE-U": u"Västmanlands län",
u"SE-O": u"Västra Götalands län",
u"SE-T": u"Örebro län",
u"SE-E": u"Östergötlands län",
u"CH-AG": u"Aargau",
u"CH-AR": u"Appenzell Ausser-Rhoden",
u"CH-AI": u"Appenzell Inner-Rhoden",
u"CH-BL": u"Basel-Landschaft",
u"CH-BS": u"Basel-Stadt",
u"CH-BE": u"Bern",
u"CH-FR": u"Freiburg",
u"CH-GE": u"Geneve",
u"CH-GL": u"Glarus",
u"CH-GR": u"Graubünden",
u"CH-JU": u"Jura",
u"CH-LU": u"Luzern",
u"CH-NE": u"Neuchatel",
u"CH-NW": u"Nidwalden",
u"CH-OW": u"Obwalden",
u"CH-SG": u"Sankt Gallen",
u"CH-SH": u"Schaffhausen",
u"CH-SZ": u"Schwyz",
u"CH-SO": u"Solothurn",
u"CH-TG": u"Thurgau",
u"CH-TI": u"Ticino",
u"CH-UR": u"Uri",
u"CH-VS": u"Wallis",
u"CH-VD": u"Vaud",
u"CH-ZG": u"Zug",
u"CH-ZH": u"Zürich",
u"SY-HA": u"Al Ḩasakah",
u"SY-LA": u"Al Lādhiqīyah",
u"SY-QU": u"Al Qunayţirah",
u"SY-RA": u"Ar Raqqah",
u"SY-SU": u"As Suwaydā'",
u"SY-DR": u"Dar’ā",
u"SY-DY": u"Dayr az Zawr",
u"SY-DI": u"Dimashq",
u"SY-HL": u"Ḩalab",
u"SY-HM": u"Ḩamāh",
u"SY-HI": u"Ḩimş",
u"SY-ID": u"Idlib",
u"SY-RD": u"Rīf Dimashq",
u"SY-TA": u"Ţarţūs",
u"TW-KHH": u"Kaohsiung",
u"TW-TPE": u"Taipei",
u"TW-CYI": u"Chiayi",
u"TW-HSZ": u"Hsinchu",
u"TW-KEE": u"Keelung",
u"TW-TXG": u"Taichung",
u"TW-TNN": u"Tainan",
u"TW-CHA": u"Changhua",
u"TW-HUA": u"Hualien",
u"TW-ILA": u"Ilan",
u"TW-MIA": u"Miaoli",
u"TW-NAN": u"Nantou",
u"TW-PEN": u"Penghu",
u"TW-PIF": u"Pingtung",
u"TW-TTT": u"Taitung",
u"TW-TAO": u"Taoyuan",
u"TW-YUN": u"Yunlin",
u"TJ-KR": u"Karategin",
u"TJ-KT": u"Khatlon",
u"TJ-LN": u"Leninabad",
u"TJ-GB": u"Gorno-Badakhshan",
u"TZ-01": u"Arusha",
u"TZ-02": u"Dar-es-Salaam",
u"TZ-03": u"Dodoma",
u"TZ-04": u"Iringa",
u"TZ-05": u"Kagera",
u"TZ-06": u"Kaskazini Pemba (Pemba North)",
u"TZ-07": u"Kaskazini Unguja (Zanzibar North)",
u"TZ-08": u"Kigoma",
u"TZ-09": u"Kilimanjaro",
u"TZ-10": u"Kusini Pemba (Pemba South)",
u"TZ-11": u"Kusini Unguja (Zanzibar South)",
u"TZ-12": u"Lindi",
u"TZ-13": u"Mara",
u"TZ-14": u"Mbeya",
u"TZ-15": u"Mjini Magharibi (Zanzibar West)",
u"TZ-16": u"Morogoro",
u"TZ-17": u"Mtwara",
u"TZ-18": u"Mwanza",
u"TZ-19": u"Pwani (Coast)",
u"TZ-20": u"Rukwa",
u"TZ-21": u"Ruvuma",
u"TZ-22": u"Shinyanga",
u"TZ-23": u"Singida",
u"TZ-24": u"Tabora",
u"TZ-25": u"Tanga",
u"TH-10": u"Krung Thep Maha Nakhon [Bangkok]",
u"TH-S": u"Phatthaya",
u"TH-37": u"Amnat Charoen",
u"TH-15": u"Ang Thong",
u"TH-31": u"Buri Ram",
u"TH-24": u"Chachoengsao",
u"TH-18": u"Chai Nat",
u"TH-36": u"Chaiyaphum",
u"TH-22": u"Chanthaburi",
u"TH-50": u"Chiang Mai",
u"TH-57": u"Chiang Rai",
u"TH-20": u"Chon Buri",
u"TH-86": u"Chumphon",
u"TH-46": u"Kalasin",
u"TH-62": u"Kamphaeng Phet",
u"TH-71": u"Kanchanaburi",
u"TH-40": u"Khon Kaen",
u"TH-81": u"Krabi",
u"TH-52": u"Lampang",
u"TH-51": u"Lamphun",
u"TH-42": u"Loei",
u"TH-16": u"Lop Buri",
u"TH-58": u"Mae Hong Son",
u"TH-44": u"Maha Sarakham",
u"TH-49": u"Mukdahan",
u"TH-26": u"Nakhon Nayok",
u"TH-73": u"Nakhon Pathom",
u"TH-48": u"Nakhon Phanom",
u"TH-30": u"Nakhon Ratchasima",
u"TH-60": u"Nakhon Sawan",
u"TH-80": u"Nakhon Si Thammarat",
u"TH-55": u"Nan",
u"TH-96": u"Narathiwat",
u"TH-39": u"Nong Bua Lam Phu",
u"TH-43": u"Nong Khai",
u"TH-12": u"Nonthaburi",
u"TH-13": u"Pathum Thani",
u"TH-94": u"Pattani",
u"TH-82": u"Phangnga",
u"TH-93": u"Phatthalung",
u"TH-56": u"Phayao",
u"TH-67": u"Phetchabun",
u"TH-76": u"Phetchaburi",
u"TH-66": u"Phichit",
u"TH-65": u"Phitsanulok",
u"TH-54": u"Phrae",
u"TH-14": u"Phra Nakhon Si Ayutthaya",
u"TH-83": u"Phuket",
u"TH-25": u"Prachin Buri",
u"TH-77": u"Prachuap Khiri Khan",
u"TH-85": u"Ranong",
u"TH-70": u"Ratchaburi",
u"TH-21": u"Rayong",
u"TH-45": u"Roi Et",
u"TH-27": u"Sa Kaeo",
u"TH-47": u"Sakon Nakhon",
u"TH-11": u"Samut Prakan",
u"TH-74": u"Samut Sakhon",
u"TH-75": u"Samut Songkhram",
u"TH-19": u"Saraburi",
u"TH-91": u"Satun",
u"TH-17": u"Sing Buri",
u"TH-33": u"Si Sa Ket",
u"TH-90": u"Songkhla",
u"TH-64": u"Sukhothai",
u"TH-72": u"Suphan Buri",
u"TH-84": u"Surat Thani",
u"TH-32": u"Surin",
u"TH-63": u"Tak",
u"TH-92": u"Trang",
u"TH-23": u"Trat",
u"TH-34": u"Ubon Ratchathani",
u"TH-41": u"Udon Thani",
u"TH-61": u"Uthai Thani",
u"TH-53": u"Uttaradit",
u"TH-95": u"Yala",
u"TH-35": u"Yasothon",
u"TG-C": u"Centre",
u"TG-K": u"Kara",
u"TG-M": u"Maritime (Région)",
u"TG-P": u"Plateaux",
u"TG-S": u"Savannes",
u"TK-TK": u"Tokelau",
u"TO-TO": u"Tonga",
u"TT-CTT": u"Couva-Tabaquite-Talparo",
u"TT-DMN": u"Diego Martin",
u"TT-ETO": u"Eastern Tobago",
u"TT-PED": u"Penal-Debe",
u"TT-PRT": u"Princes Town",
u"TT-RCM": u"Rio Claro-Mayaro",
u"TT-SGE": u"Sangre Grande",
u"TT-SJL": u"San Juan-Laventille",
u"TT-SIP": u"Siparia",
u"TT-TUP": u"Tunapuna-Piarco",
u"TT-WTO": u"Western Tobago",
u"TT-ARI": u"Arima",
u"TT-CHA": u"Chaguanas",
u"TT-PTF": u"Point Fortin",
u"TT-POS": u"Port of Spain",
u"TT-SFO": u"San Fernando",
u"TN-31": u"Béja",
u"TN-13": u"Ben Arous",
u"TN-23": u"Bizerte",
u"TN-81": u"Gabès",
u"TN-71": u"Gafsa",
u"TN-32": u"Jendouba",
u"TN-41": u"Kairouan",
u"TN-42": u"Kasserine",
u"TN-73": u"Kebili",
u"TN-12": u"L'Ariana",
u"TN-33": u"Le Kef",
u"TN-53": u"Mahdia",
u"TN-82": u"Medenine",
u"TN-52": u"Monastir",
u"TN-21": u"Nabeul",
u"TN-61": u"Sfax",
u"TN-43": u"Sidi Bouzid",
u"TN-34": u"Siliana",
u"TN-51": u"Sousse",
u"TN-83": u"Tataouine",
u"TN-72": u"Tozeur",
u"TN-11": u"Tunis",
u"TN-22": u"Zaghouan",
u"TR-01": u"Adana",
u"TR-02": u"Adiyaman",
u"TR-03": u"Afyon",
u"TR-04": u"Ağrı",
u"TR-68": u"Aksaray",
u"TR-05": u"Amasya",
u"TR-06": u"Ankara",
u"TR-07": u"Antalya",
u"TR-75": u"Ardahan",
u"TR-08": u"Artvin",
u"TR-09": u"Aydin",
u"TR-10": u"Balıkesir",
u"TR-74": u"Bartın",
u"TR-72": u"Batman",
u"TR-69": u"Bayburt",
u"TR-11": u"Bilecik",
u"TR-12": u"Bingöl",
u"TR-13": u"Bitlis",
u"TR-14": u"Bolu",
u"TR-15": u"Burdur",
u"TR-16": u"Bursa",
u"TR-17": u"Çanakkale",
u"TR-18": u"Çankırı",
u"TR-19": u"Çorum",
u"TR-20": u"Denizli",
u"TR-21": u"Diyarbakır",
u"TR-22": u"Edirne",
u"TR-23": u"Elaziğ",
u"TR-24": u"Erzincan",
u"TR-25": u"Erzurum",
u"TR-26": u"Eskişehir",
u"TR-27": u"Gaziantep",
u"TR-28": u"Giresun",
u"TR-29": u"Gümüşhane",
u"TR-30": u"Hakkari",
u"TR-31": u"Hatay",
u"TR-76": u"Iğdir",
u"TR-32": u"Isparta",
u"TR-33": u"İçel",
u"TR-34": u"İstanbul",
u"TR-35": u"İzmir",
u"TR-46": u"Kahramanmaraş",
u"TR-78": u"Karabük",
u"TR-70": u"Karaman",
u"TR-36": u"Kars",
u"TR-37": u"Kastamonu",
u"TR-38": u"Kayseri",
u"TR-71": u"Kırıkkale",
u"TR-39": u"Kırklareli",
u"TR-40": u"Kırşehir",
u"TR-79": u"Kilis",
u"TR-41": u"Kocaeli",
u"TR-42": u"Konya",
u"TR-43": u"Kütahya",
u"TR-44": u"Malatya",
u"TR-4S": u"Manisa",
u"TR-47": u"Mardin",
u"TR-48": u"Muğla",
u"TR-49": u"Muş",
u"TR-SO": u"Nevşehir",
u"TR-51": u"Niğde",
u"TR-52": u"Ordu",
u"TR-53": u"Rize",
u"TR-54": u"Sakarya",
u"TR-SS": u"Samsun",
u"TR-56": u"Siirt",
u"TR-57": u"Sinop",
u"TR-S8": u"Sivas",
u"TR-63": u"Şanlıurfa",
u"TR-73": u"Şirnak",
u"TR-59": u"Tekirdağ",
u"TR-60": u"Tokat",
u"TR-61": u"Trabzon",
u"TR-62": u"Tunceli",
u"TR-64": u"Uşak",
u"TR-65": u"Van",
u"TR-77": u"Yalova",
u"TR-66": u"Yozgat",
u"TR-67": u"Zonguldak",
u"TM-A": u"Ahal",
u"TM-B": u"Balkan",
u"TM-D": u"Daşhowuz",
u"TM-L": u"Lebap",
u"TM-M": u"Mary",
u"TC-TC": u"Turks & Caicos Islands",
u"TV-TV": u"Tuvalu",
u"UG-APA": u"Apac",
u"UG-ARU": u"Arua",
u"UG-BUN": u"Bundibugyo",
u"UG-BUS": u"Bushenyi",
u"UG-GUL": u"Gulu",
u"UG-HOI": u"Hoima",
u"UG-IGA": u"Iganga",
u"UG-JIN": u"Jinja",
u"UG-KBL": u"Kabale",
u"UG-KBR": u"Kabarole",
u"UG-KLG": u"Kalangala",
u"UG-KLA": u"Kampala",
u"UG-KLI": u"Kamuli",
u"UG-KAP": u"Kapchorwa",
u"UG-KAS": u"Kasese",
u"UG-KLE": u"Kibaale",
u"UG-KIB": u"Kiboga",
u"UG-KIS": u"Kisoro",
u"UG-KIT": u"Kitgum",
u"UG-KOT": u"Kotido",
u"UG-KUM": u"Kumi",
u"UG-LIR": u"Lira",
u"UG-LUW": u"Luwero",
u"UG-MSK": u"Masaka",
u"UG-MSI": u"Masindi",
u"UG-MBL": u"Mbale",
u"UG-MBR": u"Mbarara",
u"UG-MOR": u"Moroto",
u"UG-MOY": u"Moyo",
u"UG-MPI": u"Mpigi",
u"UG-MUB": u"Mubende",
u"UG-MUK": u"Mukono",
u"UG-NEB": u"Nebbi",
u"UG-NTU": u"Ntungamo",
u"UG-PAL": u"Pallisa",
u"UG-RAK": u"Rakai",
u"UG-RUK": u"Rukungiri",
u"UG-SOR": u"Soroti",
u"UG-TOR": u"Tororo",
u"UA-71": u"Cherkas'ka Oblast'",
u"UA-74": u"Chernihivs'ka Oblast'",
u"UA-77": u"Chernivets'ka Oblast'",
u"UA-12": u"Dnipropetrovs'ka Oblast'",
u"UA-14": u"Donets'ka Oblast'",
u"UA-26": u"Ivano-Frankivs'ka Oblast'",
u"UA-63": u"Kharkivs'ka Oblast'",
u"UA-65": u"Khersons'ka Oblast'",
u"UA-68": u"Khmel'nyts'ka Oblast'",
u"UA-35": u"Kirovohrads'ka Oblast'",
u"UA-32": u"Kyïvs'ka Oblast'",
u"UA-09": u"Luhans'ka Oblast'",
u"UA-46": u"L'vivs'ka Oblast'",
u"UA-48": u"Mykolaïvs'ka Oblast'",
u"UA-51": u"Odes'ka Oblast'",
u"UA-53": u"Poltavs'ka Oblast'",
u"UA-56": u"Rivnens'ka Oblast'",
u"UA-59": u"Sums'ka Oblast'",
u"UA-61": u"Ternopil's'ka Oblast'",
u"UA-05": u"Vinnyts'ka Oblast'",
u"UA-07": u"Volyns'ka Oblast'",
u"UA-21": u"Zakarpats'ka Oblast'",
u"UA-23": u"Zaporiz'ka Oblast'",
u"UA-18": u"Zhytomyrs'ka Oblast'",
u"UA-43": u"Respublika Krym",
u"UA-30": u"Kyïv",
u"UA-40": u"Sevastopol'",
u"AE-AZ": u"Abū Zaby (Abu Dhabi)",
u"AE-AJ": u"‘Ajmān",
u"AE-FU": u"Al Fujayrah",
u"AE-SH": u"Ash Shāriqah (Sharjah)",
u"AE-DU": u"Dubayy (Dubai)",
u"AE-RK": u"R'as al Khaymah",
u"AE-UQ": u"Umm al Qaywayn",
u"US-AL": u"Alabama",
u"US-AK": u"Alaska",
u"US-AZ": u"Arizona",
u"US-AR": u"Arkansas",
u"US-CA": u"California",
u"US-CO": u"Colorado",
u"US-CT": u"Connecticut",
u"US-DE": u"Delaware",
u"US-FL": u"Florida",
u"US-GA": u"Georgia",
u"US-HI": u"Hawaii",
u"US-ID": u"Idaho",
u"US-IL": u"Illinois",
u"US-IN": u"Indiana",
u"US-IA": u"Iowa",
u"US-KS": u"Kansas",
u"US-KY": u"Kentucky",
u"US-LA": u"Louisiana",
u"US-ME": u"Maine",
u"US-MD": u"Maryland",
u"US-MA": u"Massachusetts",
u"US-MI": u"Michigan",
u"US-MN": u"Minnesota",
u"US-MS": u"Mississippi",
u"US-MO": u"Missouri",
u"US-MT": u"Montana",
u"US-NE": u"Nebraska",
u"US-NV": u"Nevada",
u"US-NH": u"New Hampshire",
u"US-NJ": u"New Jersey",
u"US-NM": u"New Mexico",
u"US-NY": u"New York",
u"US-NC": u"North Carolina",
u"US-ND": u"North Dakota",
u"US-OH": u"Ohio",
u"US-OK": u"Oklahoma",
u"US-OR": u"Oregon",
u"US-PA": u"Pennsylvania",
u"US-RI": u"Rhode Island",
u"US-SC": u"South Carolina",
u"US-SD": u"South Dakota",
u"US-TN": u"Tennessee",
u"US-TX": u"Texas",
u"US-UT": u"Utah",
u"US-VT": u"Vermont",
u"US-VA": u"Virginia",
u"US-WA": u"Washington",
u"US-WV": u"West Virginia",
u"US-WI": u"Wisconsin",
u"US-WY": u"Wyoming",
u"US-DC": u"District of Columbia",
u"US-AS": u"American Samoa",
u"US-GU": u"Guam",
u"US-MP": u"Northern Mariana Islands",
u"US-PR": u"Puerto Rico",
u"US-UM": u"United States Minor Outlying Islands",
u"US-VI": u"Virgin Islands, U.S.",
u"UY-AR": u"Artigas",
u"UY-CA": u"Canelones",
u"UY-CL": u"Cerro Largo",
u"UY-CO": u"Colonia",
u"UY-DU": u"Durazno",
u"UY-FS": u"Flores",
u"UY-FD": u"Florida",
u"UY-LA": u"Lavalleja",
u"UY-MA": u"Maldonado",
u"UY-MO": u"Montevideo",
u"UY-PA": u"Paysandú",
u"UY-RN": u"Río Negro",
u"UY-RV": u"Rivera",
u"UY-RO": u"Rocha",
u"UY-SA": u"Salto",
u"UY-SJ": u"San José",
u"UY-SO": u"Soriano",
u"UY-TA": u"Tacuarembó",
u"UY-TT": u"Treinta y Tres",
u"UZ-QR": u"Qoraqalpoghiston Respublikasi (Karakalpakstan, Respublika)",
u"UZ-AN": u"Andijon (Andizhan)",
u"UZ-BU": u"Bukhoro (Bukhara)",
u"UZ-FA": u"Farghona (Fergana)",
u"UZ-JI": u"Jizzakh (Dzhizak)",
u"UZ-KH": u"Khorazm (Khorezm)",
u"UZ-NG": u"Namangan",
u"UZ-NW": u"Nawoiy (Navoi)",
u"UZ-QA": u"Qashqadaryo (Kashkadar'ya)",
u"UZ-SA": u"Samarqand (Samarkand)",
u"UZ-SI": u"Sirdaryo (Syrdar'ya)",
u"UZ-SU": u"Surkhondaryo (Surkhandar'ya)",
u"UZ-TO": u"Toshkent (Tashkent)",
u"VU-MAP": u"Malampa",
u"VU-PAM": u"Pénama",
u"VU-SAM": u"Sanma",
u"VU-SEE": u"Shéfa",
u"VU-TAE": u"Taféa",
u"VU-TOB": u"Torba",
u"VE-A": u"Distrito Federal",
u"VE-B": u"Anzoátegui",
u"VE-C": u"Apure",
u"VE-D": u"Aragua",
u"VE-E": u"Barinas",
u"VE-F": u"Bolívar",
u"VE-G": u"Carabobo",
u"VE-H": u"Cojedes",
u"VE-I": u"Falcón",
u"VE-J": u"Guárico",
u"VE-K": u"Lara",
u"VE-L": u"Mérida",
u"VE-M": u"Miranda",
u"VE-N": u"Monagas",
u"VE-O": u"Nueva Esparta",
u"VE-P": u"Portuguesa",
u"VE-R": u"Sucre",
u"VE-S": u"Táchira",
u"VE-T": u"Trujillo",
u"VE-U": u"Yaracuy",
u"VE-V": u"Zulia",
u"VE-Z": u"Amazonas",
u"VE-Y": u"Delta Amacuro",
u"VE-W": u"Dependencias Federales",
u"VN-44": u"An Giang",
u"VN-53": u"Bat Can",
u"VN-54": u"Bat Giang",
u"VN-55": u"Bat Lieu",
u"VN-56": u"Bat Ninh",
u"VN-43": u"Ba Ria - Vung Tau",
u"VN-50": u"Ben Tre",
u"VN-31": u"Binh Dinh",
u"VN-57": u"Binh Duong",
u"VN-58": u"Binh Phuoc",
u"VN-40": u"Binh Thuan",
u"VN-59": u"Ca Mau",
u"VN-48": u"Can Tho",
u"VN-04": u"Cao Bang",
u"VN-33": u"Dac Lac",
u"VN-60": u"Da Nang, thanh pho",
u"VN-39": u"Dong Nai",
u"VN-45": u"Dong Thap",
u"VN-30": u"Gia Lai",
u"VN-03": u"Ha Giang",
u"VN-61": u"Hai Duong",
u"VN-62": u"Hai Phong, thanh pho",
u"VN-63": u"Ha Nam",
u"VN-64": u"Ha Noi, thu do",
u"VN-15": u"Ha Tay",
u"VN-23": u"Ha Tinh",
u"VN-14": u"Hoa Binh",
u"VN-65": u"Ho Chi Minh, thanh po [Sai Gon]",
u"VN-66": u"Hung Yen",
u"VN-34": u"Khanh Hoa",
u"VN-47": u"Kien Giang",
u"VN-28": u"Kon Turn",
u"VN-01": u"Lai Chau",
u"VN-35": u"Lam Dong",
u"VN-09": u"Lang Son",
u"VN-02": u"Lao Cai",
u"VN-41": u"Long An",
u"VN-67": u"Nam Dinh",
u"VN-22": u"Nghe An",
u"VN-18": u"Ninh Binh",
u"VN-36": u"Ninh Thuan",
u"VN-68": u"Phu Tho",
u"VN-32": u"Phu Yen",
u"VN-24": u"Quang Ninh",
u"VN-27": u"Quang Nam",
u"VN-29": u"Quang Ngai",
u"VN-25": u"Quang Tri",
u"VN-52": u"Sec Trang",
u"VN-05": u"Son La",
u"VN-37": u"Tay Ninh",
u"VN-20": u"Thai Binh",
u"VN-69": u"Thai Nguyen",
u"VN-21": u"Thanh Hoa",
u"VN-26": u"Thua Thien-Hue",
u"VN-46": u"Tien Giang",
u"VN-51": u"Tra Vinh",
u"VN-07": u"Tuyen Quang",
u"VN-49": u"Vinh Long",
u"VN-70": u"Vinh Yen",
u"VN-06": u"Yen Bai",
u"VG-VG": u"Virgin Islands (British)",
u"VI-VI": u"Virgin Islands (U.S.)",
u"WF-WF": u"Wallis & Futuna Islands",
u"EH-EH": u"Western Sahara",
u"YE-AB": u"Abyān",
u"YE-AD": u"‘Adan",
u"YE-BA": u"Al Bayḑā'",
u"YE-HU": u"Al Ḩudaydah",
u"YE-JA": u"Al Jawf",
u"YE-MR": u"Al Mahrah",
u"YE-MW": u"Al Maḩwit",
u"YE-DH": u"Dhamār",
u"YE-HD": u"Ḩaḑramawt",
u"YE-HJ": u"Ḩajjah",
u"YE-IB": u"Ibb",
u"YE-LA": u"Laḩij",
u"YE-MA": u"Ma'rib",
u"YE-SD": u"Şa'dah",
u"YE-SN": u"Şan‘ā'",
u"YE-SH": u"Shabwah",
u"YE-TA": u"Ta‘izz",
u"YU-CG": u"Crna Gora",
u"YU-SR": u"Srbija",
u"YU-KM": u"Kosovo-Metohija",
u"YU-VO": u"Vojvodina",
u"ZM-02": u"Central",
u"ZM-08": u"Copperbelt",
u"ZM-03": u"Eastern",
u"ZM-04": u"Luapula",
u"ZM-09": u"Lusaka",
u"ZM-05": u"Northern",
u"ZM-06": u"North-Western",
u"ZM-07": u"Southern",
u"ZM-01": u"Western",
u"ZW-BU": u"Bulawayo",
u"ZW-HA": u"Harare",
u"ZW-MA": u"Manicaland",
u"ZW-MC": u"Mashonaland Central",
u"ZW-ME": u"Mashonaland East",
u"ZW-MW": u"Mashonaland West",
u"ZW-MV": u"Masvingo",
u"ZW-MN": u"Matabeleland North",
u"ZW-MS": u"Matabeleland South",
u"ZW-MI": u"Midlands"}

def getRegionNameByCode(countryCode, regionCode):
  code = countryCode.upper() + "-" + regionCode.upper()
  if code in _dic:
    return _dic[code.upper()]
  else:
    return "Not in list"