application: eggplant-tag
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img

- url: /deleteRequest
  script: deleteRequest.app
- url: /deleteTag
  script: deleteTag.app
- url: /generateTag
  script: tagGenerator.app
- url: /request.*
  script: requestTag.app

- url: /generator/
  script: generator.app
- url: /tags/
  script: myTags.app
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
