application: eggplant-tag
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /deleteTag
  script: deleteTag.app
- url: /tag/
  script: tagGenerator.app
- url: /tags/
  script: myTags.app
- url: /request.*
  script: requestTag.app
- url: /.*
  script: main.app